-- Add pre-queuing support to stories table.
-- A queued story is one that has been pre-generated by the recommendation engine
-- but not yet "consumed" (opened) by the user.

ALTER TABLE stories
ADD COLUMN IF NOT EXISTS is_queued BOOLEAN NOT NULL DEFAULT FALSE;

-- Partial index so the "find my queued story" lookup is instant.
CREATE INDEX IF NOT EXISTS idx_stories_user_queued
  ON stories (user_id, created_at DESC)
  WHERE is_queued = TRUE;
