import type { Idiom } from "./types";

export const IDIOMS_FR: Idiom[] = [
  {
    id: "fr-id-01",
    expression: "Coûter les yeux de la tête",
    literal: "To cost the eyes of the head",
    translation: "To cost an arm and a leg",
    exampleTarget: "Cette voiture est magnifique, mais elle coûte les yeux de la tête.",
    exampleEnglish: "That car is beautiful, but it costs an arm and a leg.",
  },
  {
    id: "fr-id-02",
    expression: "Faire d'une pierre deux coups",
    literal: "To make two blows with one stone",
    translation: "To kill two birds with one stone",
    exampleTarget: "En faisant les courses en chemin, j'ai fait d'une pierre deux coups.",
    exampleEnglish: "By doing the shopping on the way, I killed two birds with one stone.",
  },
  {
    id: "fr-id-03",
    expression: "Avoir le cafard",
    literal: "To have the cockroach",
    translation: "To feel down / to have the blues",
    exampleTarget: "Depuis qu'il a déménagé, il a souvent le cafard.",
    exampleEnglish: "Since he moved, he often feels down.",
  },
  {
    id: "fr-id-04",
    expression: "Être dans les nuages",
    literal: "To be in the clouds",
    translation: "To have one's head in the clouds / to daydream",
    exampleTarget: "Arrête d'être dans les nuages et concentre-toi !",
    exampleEnglish: "Stop daydreaming and concentrate!",
  },
  {
    id: "fr-id-05",
    expression: "Faire la sourde oreille",
    literal: "To make the deaf ear",
    translation: "To turn a deaf ear / to ignore",
    exampleTarget: "Je lui ai répété plusieurs fois, mais il a fait la sourde oreille.",
    exampleEnglish: "I told him several times, but he turned a deaf ear.",
  },
  {
    id: "fr-id-06",
    expression: "Poser un lapin à quelqu'un",
    literal: "To place a rabbit on someone",
    translation: "To stand someone up",
    exampleTarget: "Elle m'a posé un lapin — j'ai attendu une heure au café.",
    exampleEnglish: "She stood me up — I waited an hour at the café.",
  },
  {
    id: "fr-id-07",
    expression: "Se retrousser les manches",
    literal: "To roll up one's sleeves",
    translation: "To roll up one's sleeves / to get to work",
    exampleTarget: "Il faut se retrousser les manches si on veut finir avant minuit.",
    exampleEnglish: "We need to roll up our sleeves if we want to finish before midnight.",
  },
  {
    id: "fr-id-08",
    expression: "Jeter l'éponge",
    literal: "To throw the sponge",
    translation: "To throw in the towel / to give up",
    exampleTarget: "Après trois tentatives, elle a jeté l'éponge.",
    exampleEnglish: "After three attempts, she threw in the towel.",
  },
  {
    id: "fr-id-09",
    expression: "Mettre les pieds dans le plat",
    literal: "To put one's feet in the dish",
    translation: "To put one's foot in it / to blunder tactlessly",
    exampleTarget: "Il a vraiment mis les pieds dans le plat en mentionnant son ex.",
    exampleEnglish: "He really put his foot in it by bringing up her ex.",
  },
  {
    id: "fr-id-10",
    expression: "C'est du gâteau",
    literal: "It's cake",
    translation: "It's a piece of cake / it's very easy",
    exampleTarget: "Cet examen ? C'était du gâteau — j'ai fini en vingt minutes.",
    exampleEnglish: "That exam? It was a piece of cake — I finished in twenty minutes.",
  },
  {
    id: "fr-id-11",
    expression: "Ne pas avoir la langue dans sa poche",
    literal: "To not have the tongue in one's pocket",
    translation: "To be outspoken / to always have something to say",
    exampleTarget: "Ma cousine n'a pas la langue dans sa poche ; elle dit tout ce qu'elle pense.",
    exampleEnglish: "My cousin is never at a loss for words; she says exactly what she thinks.",
  },
  {
    id: "fr-id-12",
    expression: "Casser les pieds à quelqu'un",
    literal: "To break someone's feet",
    translation: "To annoy / to bug someone",
    exampleTarget: "Arrête de me casser les pieds avec tes questions !",
    exampleEnglish: "Stop bugging me with your questions!",
  },
  {
    id: "fr-id-13",
    expression: "Être comme un poisson dans l'eau",
    literal: "To be like a fish in water",
    translation: "To be in one's element",
    exampleTarget: "Sur scène, elle est comme un poisson dans l'eau.",
    exampleEnglish: "On stage, she is completely in her element.",
  },
  {
    id: "fr-id-14",
    expression: "Il ne faut pas vendre la peau de l'ours avant de l'avoir tué",
    literal: "You must not sell the bear's skin before having killed it",
    translation: "Don't count your chickens before they hatch",
    exampleTarget: "On n'a pas encore gagné — il ne faut pas vendre la peau de l'ours avant de l'avoir tué.",
    exampleEnglish: "We haven't won yet — don't count your chickens before they hatch.",
  },
  {
    id: "fr-id-15",
    expression: "Prendre ses jambes à son cou",
    literal: "To take one's legs to one's neck",
    translation: "To run away as fast as possible / to take to one's heels",
    exampleTarget: "Quand il a vu le chien, il a pris ses jambes à son cou.",
    exampleEnglish: "When he saw the dog, he took to his heels.",
  },
  {
    id: "fr-id-16",
    expression: "Avoir d'autres chats à fouetter",
    literal: "To have other cats to whip",
    translation: "To have bigger fish to fry / to have more important things to do",
    exampleTarget: "Je ne peux pas t'aider maintenant — j'ai d'autres chats à fouetter.",
    exampleEnglish: "I can't help you now — I have bigger fish to fry.",
  },
  {
    id: "fr-id-17",
    expression: "Donner sa langue au chat",
    literal: "To give one's tongue to the cat",
    translation: "To give up guessing",
    exampleTarget: "— Tu sais ce que c'est ? — Je donne ma langue au chat.",
    exampleEnglish: "— Do you know what it is? — I give up.",
  },
  {
    id: "fr-id-18",
    expression: "Avoir le beurre et l'argent du beurre",
    literal: "To have the butter and the money from the butter",
    translation: "To have it both ways / to want your cake and eat it too",
    exampleTarget: "Tu ne peux pas avoir le beurre et l'argent du beurre.",
    exampleEnglish: "You can't have it both ways.",
  },
  {
    id: "fr-id-19",
    expression: "Il pleut des cordes",
    literal: "It rains ropes",
    translation: "It's raining cats and dogs",
    exampleTarget: "On ne peut pas sortir — il pleut des cordes dehors.",
    exampleEnglish: "We can't go out — it's raining cats and dogs outside.",
  },
  {
    id: "fr-id-20",
    expression: "Avoir le cœur sur la main",
    literal: "To have the heart on one's hand",
    translation: "To be very generous / to wear one's heart on one's sleeve",
    exampleTarget: "Elle a toujours le cœur sur la main ; elle aide tout le monde.",
    exampleEnglish: "She always wears her heart on her sleeve; she helps everyone.",
  },
];
