import type { Idiom } from "./types";

export const IDIOMS_ES: Idiom[] = [
  {
    id: "es-id-01",
    expression: "Costar un ojo de la cara",
    literal: "To cost an eye from the face",
    translation: "To cost an arm and a leg",
    exampleTarget: "Ese restaurante es buenísimo, pero cuesta un ojo de la cara.",
    exampleEnglish: "That restaurant is fantastic, but it costs an arm and a leg.",
  },
  {
    id: "es-id-02",
    expression: "No hay mal que por bien no venga",
    literal: "There is no bad thing that doesn't come with something good",
    translation: "Every cloud has a silver lining",
    exampleTarget: "Perdí el autobús, pero así conocí a mi mejor amiga. No hay mal que por bien no venga.",
    exampleEnglish: "I missed the bus, but that's how I met my best friend. Every cloud has a silver lining.",
  },
  {
    id: "es-id-03",
    expression: "Matar dos pájaros de un tiro",
    literal: "To kill two birds with one shot",
    translation: "To kill two birds with one stone",
    exampleTarget: "Voy al gimnasio antes del trabajo para matar dos pájaros de un tiro.",
    exampleEnglish: "I go to the gym before work to kill two birds with one stone.",
  },
  {
    id: "es-id-04",
    expression: "Tener mala leche",
    literal: "To have bad milk",
    translation: "To be in a bad mood / to be bad-tempered",
    exampleTarget: "Hoy tiene muy mala leche; mejor no le hables.",
    exampleEnglish: "He's in a really bad mood today; better not talk to him.",
  },
  {
    id: "es-id-05",
    expression: "Estar en las nubes",
    literal: "To be in the clouds",
    translation: "To have one's head in the clouds / to daydream",
    exampleTarget: "Durante la clase, ella estaba en las nubes y no escuchó nada.",
    exampleEnglish: "During class, she had her head in the clouds and didn't hear a thing.",
  },
  {
    id: "es-id-06",
    expression: "Hacer la vista gorda",
    literal: "To make the fat view",
    translation: "To turn a blind eye / to look the other way",
    exampleTarget: "El profesor hizo la vista gorda cuando llegamos tarde.",
    exampleEnglish: "The teacher turned a blind eye when we arrived late.",
  },
  {
    id: "es-id-07",
    expression: "Ponerse las pilas",
    literal: "To put in the batteries",
    translation: "To get one's act together / to shape up",
    exampleTarget: "Si quieres pasar el examen, tienes que ponerte las pilas.",
    exampleEnglish: "If you want to pass the exam, you need to get your act together.",
  },
  {
    id: "es-id-08",
    expression: "Tirar la toalla",
    literal: "To throw the towel",
    translation: "To throw in the towel / to give up",
    exampleTarget: "Después de meses intentándolo, decidió tirar la toalla.",
    exampleEnglish: "After months of trying, he decided to throw in the towel.",
  },
  {
    id: "es-id-09",
    expression: "Dar en el clavo",
    literal: "To hit the nail",
    translation: "To hit the nail on the head / to be spot-on",
    exampleTarget: "Tu análisis dio en el clavo; eso es exactamente el problema.",
    exampleEnglish: "Your analysis hit the nail on the head; that's exactly the problem.",
  },
  {
    id: "es-id-10",
    expression: "Ser pan comido",
    literal: "To be eaten bread",
    translation: "To be a piece of cake / to be very easy",
    exampleTarget: "¿La entrevista? Fue pan comido — me sabía todas las respuestas.",
    exampleEnglish: "The interview? It was a piece of cake — I knew all the answers.",
  },
  {
    id: "es-id-11",
    expression: "No tener pelos en la lengua",
    literal: "To have no hairs on the tongue",
    translation: "To speak one's mind / to not mince words",
    exampleTarget: "Mi abuela no tiene pelos en la lengua; siempre dice lo que piensa.",
    exampleEnglish: "My grandmother never minces words; she always says what she thinks.",
  },
  {
    id: "es-id-12",
    expression: "Dar la lata",
    literal: "To give the can",
    translation: "To bug someone / to be a nuisance",
    exampleTarget: "Los niños le daban la lata a su madre durante todo el viaje.",
    exampleEnglish: "The kids were bugging their mother the entire trip.",
  },
  {
    id: "es-id-13",
    expression: "Estar como pez en el agua",
    literal: "To be like a fish in the water",
    translation: "To be in one's element / to feel completely at home",
    exampleTarget: "En la cocina, mi hermana está como pez en el agua.",
    exampleEnglish: "In the kitchen, my sister is completely in her element.",
  },
  {
    id: "es-id-14",
    expression: "Llueve sobre mojado",
    literal: "It rains on the wet",
    translation: "When it rains, it pours / bad things keep piling up",
    exampleTarget: "Primero el coche, luego el trabajo... llueve sobre mojado.",
    exampleEnglish: "First the car, then the job... when it rains, it pours.",
  },
  {
    id: "es-id-15",
    expression: "A otro perro con ese hueso",
    literal: "To another dog with that bone",
    translation: "Tell it to someone who'll believe it / I'm not buying it",
    exampleTarget: "¿Que trabajaste todo el fin de semana? A otro perro con ese hueso.",
    exampleEnglish: "You worked all weekend? Tell it to someone who'll believe it.",
  },
  {
    id: "es-id-16",
    expression: "Tomar el pelo",
    literal: "To take the hair",
    translation: "To pull someone's leg / to tease or fool someone",
    exampleTarget: "¿Me estás tomando el pelo? ¡Eso es imposible!",
    exampleEnglish: "Are you pulling my leg? That's impossible!",
  },
  {
    id: "es-id-17",
    expression: "No hay de qué",
    literal: "There's nothing of which",
    translation: "You're welcome / don't mention it",
    exampleTarget: "— Gracias por la ayuda. — No hay de qué.",
    exampleEnglish: "— Thank you for the help. — Don't mention it.",
  },
  {
    id: "es-id-18",
    expression: "Meter la pata",
    literal: "To put in the paw (foot)",
    translation: "To put one's foot in it / to blunder",
    exampleTarget: "Metí la pata al mencionar su ex delante de todos.",
    exampleEnglish: "I put my foot in it when I mentioned his ex in front of everyone.",
  },
  {
    id: "es-id-19",
    expression: "Coger el toro por los cuernos",
    literal: "To grab the bull by the horns",
    translation: "To take the bull by the horns / to tackle a problem head-on",
    exampleTarget: "Es hora de coger el toro por los cuernos y hablar con tu jefe.",
    exampleEnglish: "It's time to take the bull by the horns and talk to your boss.",
  },
  {
    id: "es-id-20",
    expression: "Echar agua al mar",
    literal: "To throw water into the sea",
    translation: "To do something pointless / to carry coals to Newcastle",
    exampleTarget: "Darle consejos a ese hombre es echar agua al mar.",
    exampleEnglish: "Giving that man advice is a complete waste of time.",
  },
];
