import type { WordEntry } from "./bank";

export const WORD_BANK_FR: WordEntry[] = [
  {
    word: "la flânerie",
    partOfSpeech: "noun",
    gender: "feminine",
    ipa: "/fla.n(ə).ʁi/",
    definition: "The art of leisurely strolling through city streets with no particular destination.",
    example: "Il passa l'après-midi en flânerie dans les ruelles de Paris.",
    exampleEn: "He spent the afternoon leisurely wandering the streets of Paris.",
  },
  {
    word: "s'épanouir",
    partOfSpeech: "verb",
    ipa: "/s‿e.pa.nwiʁ/",
    definition: "To blossom, flourish, or come into one's full potential.",
    example: "Elle s'est épanouie depuis qu'elle a trouvé sa passion.",
    exampleEn: "She has blossomed since she found her passion.",
  },
  {
    word: "le dépaysement",
    partOfSpeech: "noun",
    gender: "masculine",
    definition: "The disorienting yet refreshing feeling of being in a foreign country or unfamiliar surroundings.",
    example: "Le dépaysement complet de ce voyage lui a fait du bien.",
    exampleEn: "The complete change of scenery from this trip did him a world of good.",
  },
  {
    word: "saugrenu",
    partOfSpeech: "adjective",
    ipa: "/so.ɡʁə.ny/",
    definition: "Absurd, preposterous, or utterly incongruous.",
    example: "Il a eu l'idée saugrenue de peindre sa voiture en rose vif.",
    exampleEn: "He had the absurd idea of painting his car bright pink.",
  },
  {
    word: "la quiétude",
    partOfSpeech: "noun",
    gender: "feminine",
    ipa: "/kjɛ.tyd/",
    definition: "A state of peace, calm, and complete tranquillity.",
    example: "Rien ne trouble la quiétude de ce village de montagne.",
    exampleEn: "Nothing disturbs the tranquillity of this mountain village.",
  },
  {
    word: "effleurer",
    partOfSpeech: "verb",
    ipa: "/e.flœ.ʁe/",
    definition: "To touch or brush very lightly; to skim the surface of an idea without exploring it.",
    example: "Il a effleuré le sujet sans vraiment l'approfondir.",
    exampleEn: "He barely touched on the subject without really going into it.",
  },
  {
    word: "la fougue",
    partOfSpeech: "noun",
    gender: "feminine",
    ipa: "/fuɡ/",
    definition: "Fiery passion, ardour, or impetuous spirit.",
    example: "Elle a défendu ses idées avec une fougue remarquable.",
    exampleEn: "She defended her ideas with remarkable passion.",
  },
  {
    word: "bienveillant",
    partOfSpeech: "adjective",
    ipa: "/bjɛ̃.vɛ.jɑ̃/",
    definition: "Benevolent, warm-hearted, and well-intentioned toward others.",
    example: "Un regard bienveillant peut transformer une journée difficile.",
    exampleEn: "A kind look can turn a difficult day around.",
  },
  {
    word: "le frisson",
    partOfSpeech: "noun",
    gender: "masculine",
    ipa: "/fʁi.sɔ̃/",
    definition: "A sudden shiver of excitement, fear, or aesthetic pleasure.",
    example: "Ce morceau de musique lui donne des frissons à chaque écoute.",
    exampleEn: "This piece of music gives her chills every time she hears it.",
  },
  {
    word: "se morfondre",
    partOfSpeech: "verb",
    ipa: "/sə.mɔʁ.fɔ̃dʁ/",
    definition: "To mope, languish, or wait in gloomy anxiety for something that does not come.",
    example: "Ne te morfonds pas à l'attendre — il finira par arriver.",
    exampleEn: "Don't mope waiting for him — he'll eventually show up.",
  },
  {
    word: "lumineux",
    partOfSpeech: "adjective",
    ipa: "/ly.mi.nø/",
    definition: "Bright, radiant, or intellectually brilliant; full of light.",
    example: "Son explication lumineuse a tout éclairci en quelques minutes.",
    exampleEn: "Her brilliant explanation clarified everything in just a few minutes.",
  },
  {
    word: "le sillage",
    partOfSpeech: "noun",
    gender: "masculine",
    ipa: "/si.jaʒ/",
    definition: "The wake left behind a ship or aircraft; by extension, a lasting trail or influence.",
    example: "Dans le sillage de cet artiste, de nombreux talents ont émergé.",
    exampleEn: "In the wake of this artist, many talents have emerged.",
  },
  {
    word: "jubiler",
    partOfSpeech: "verb",
    ipa: "/ʒy.bi.le/",
    definition: "To be overjoyed, exult, or feel intense delight.",
    example: "Les enfants jubilaient à l'annonce des vacances.",
    exampleEn: "The children were overjoyed at the announcement of the holidays.",
  },
  {
    word: "le recueillement",
    partOfSpeech: "noun",
    gender: "masculine",
    definition: "A state of quiet contemplation, reflection, or spiritual meditation.",
    example: "Il avait besoin d'un moment de recueillement avant de décider.",
    exampleEn: "He needed a moment of quiet reflection before deciding.",
  },
  {
    word: "fougueux",
    partOfSpeech: "adjective",
    ipa: "/fu.ɡø/",
    definition: "Spirited, fiery, or impetuous — full of unrestrained energy.",
    example: "Ce cheval fougueux était difficile à maîtriser.",
    exampleEn: "This spirited horse was difficult to control.",
  },
  {
    word: "la mélancolie",
    partOfSpeech: "noun",
    gender: "feminine",
    ipa: "/me.lɑ̃.kɔ.li/",
    definition: "A deep, pensive, and long-lasting sadness; gentle wistfulness.",
    example: "Une douce mélancolie l'envahissait au crépuscule.",
    exampleEn: "A gentle melancholy washed over her at dusk.",
  },
  {
    word: "effervescent",
    partOfSpeech: "adjective",
    ipa: "/e.fɛʁ.vɛ.sɑ̃/",
    definition: "Bubbling with energy, enthusiasm, or vivacity; lively.",
    example: "Son humeur effervescente rendait chaque réunion agréable.",
    exampleEn: "Her bubbly mood made every meeting enjoyable.",
  },
  {
    word: "la rêverie",
    partOfSpeech: "noun",
    gender: "feminine",
    ipa: "/ʁɛv.ʁi/",
    definition: "A pleasant daydream or state of pleasant abstraction from reality.",
    example: "Perdu dans sa rêverie, il n'entendit pas le téléphone sonner.",
    exampleEn: "Lost in his daydream, he didn't hear the phone ring.",
  },
  {
    word: "assouvir",
    partOfSpeech: "verb",
    ipa: "/a.su.viʁ/",
    definition: "To satisfy fully or gratify a desire, hunger, or craving.",
    example: "Rien n'assouvissait sa soif de connaissances.",
    exampleEn: "Nothing could satisfy his thirst for knowledge.",
  },
  {
    word: "le savoir-vivre",
    partOfSpeech: "noun",
    gender: "masculine",
    definition: "Good manners, social grace, and the knowledge of how to behave in polite society.",
    example: "Son savoir-vivre impeccable lui ouvrait toutes les portes.",
    exampleEn: "His impeccable social grace opened every door for him.",
  },
  {
    word: "pétillant",
    partOfSpeech: "adjective",
    ipa: "/pe.ti.jɑ̃/",
    definition: "Sparkling, bubbly, or vivacious — applied to personality as well as carbonated drinks.",
    example: "Elle a un regard pétillant qui met les gens à l'aise.",
    exampleEn: "She has a sparkling gaze that puts people at ease.",
  },
  {
    word: "se ressourcer",
    partOfSpeech: "verb",
    definition: "To recharge one's energy or spirit by reconnecting with a calming environment or activity.",
    example: "Il part à la campagne chaque week-end pour se ressourcer.",
    exampleEn: "He goes to the countryside every weekend to recharge.",
  },
  {
    word: "l'émerveillement",
    partOfSpeech: "noun",
    gender: "masculine",
    ipa: "/e.mɛʁ.vɛj.mɑ̃/",
    definition: "A state of wonder and amazement; the capacity to be filled with awe.",
    example: "L'émerveillement des enfants devant la neige est inoubliable.",
    exampleEn: "Children's wonder at the sight of snow is unforgettable.",
  },
  {
    word: "intransigeant",
    partOfSpeech: "adjective",
    ipa: "/ɛ̃.tʁɑ̃.zi.ʒɑ̃/",
    definition: "Uncompromising and inflexible; refusing to make any concession.",
    example: "Il était intransigeant sur la qualité de son travail.",
    exampleEn: "He was uncompromising about the quality of his work.",
  },
  {
    word: "la tendresse",
    partOfSpeech: "noun",
    gender: "feminine",
    ipa: "/tɑ̃.dʁɛs/",
    definition: "Tenderness, gentleness, or warm affection shown toward someone.",
    example: "Il regardait les photos de sa famille avec tendresse.",
    exampleEn: "He looked at his family photos with tenderness.",
  },
  {
    word: "frémir",
    partOfSpeech: "verb",
    ipa: "/fʁe.miʁ/",
    definition: "To tremble, quiver, or shudder — with emotion, cold, or anticipation.",
    example: "Les feuilles frémissaient sous la brise du soir.",
    exampleEn: "The leaves trembled in the evening breeze.",
  },
  {
    word: "la convivialité",
    partOfSpeech: "noun",
    gender: "feminine",
    definition: "A warm, welcoming atmosphere of togetherness and easy sociability.",
    example: "La convivialité de ce restaurant en fait un endroit idéal.",
    exampleEn: "The warm atmosphere of this restaurant makes it an ideal spot.",
  },
  {
    word: "inébranlable",
    partOfSpeech: "adjective",
    ipa: "/i.ne.bʁɑ̃.labl/",
    definition: "Unshakeable, steadfast, and impossible to move from one's convictions.",
    example: "Sa confiance en lui était inébranlable malgré les obstacles.",
    exampleEn: "His self-confidence was unshakeable despite the obstacles.",
  },
  {
    word: "le vagabondage",
    partOfSpeech: "noun",
    gender: "masculine",
    definition: "Wandering or roaming without a fixed destination; aimless drifting.",
    example: "Son vagabondage à travers l'Europe dura trois ans.",
    exampleEn: "His wandering across Europe lasted three years.",
  },
  {
    word: "rayonner",
    partOfSpeech: "verb",
    ipa: "/ʁɛ.jɔ.ne/",
    definition: "To radiate light, warmth, or happiness; to shine outward from a centre.",
    example: "Elle rayonnait de joie le soir de son mariage.",
    exampleEn: "She radiated joy on the evening of her wedding.",
  },
];
