export type CountryFacts = {
  fun_facts: string[];
  cultural_note: string;
  language_note: string;
  famous_for: string;
  must_know_phrase: string;
  capital?: string;
  population?: number;
  region?: string;
  subregion?: string;
};

type Lang = "es" | "fr";

const ES_FACTS: Record<string, CountryFacts> = {
  AR: {
    capital: "Buenos Aires", population: 46000000, region: "Americas", subregion: "South America",
    fun_facts: ["Home to the widest avenue in the world (9 de Julio).", "Tango was born in Río de la Plata ports.", "Patagonia holds some of Earth's southernmost cities.", "Argentine Spanish often uses vos instead of tú.", "The country has won multiple FIFA World Cups."],
    cultural_note: "Argentine culture blends European immigration with criollo traditions. Asados, football, and late dinners shape social life.",
    language_note: "Rioplatense Spanish features voseo and a distinctive 'sh/zh' sound for ll/y (yeísmo rehilado).",
    famous_for: "Tango, beef asado, Patagonia, football",
    must_know_phrase: "Che, ¿todo bien? — Hey, everything good?",
  },
  BO: {
    capital: "Sucre (constitutional) / La Paz (seat of government)", population: 12000000, region: "Americas", subregion: "South America",
    fun_facts: ["La Paz is one of the world's highest administrative capitals.", "Bolivia has 36 official languages including Spanish.", "Salar de Uyuni is the world's largest salt flat.", "The country is landlocked but maintains a navy tradition.", "Cholita wrestling is a popular cultural spectacle."],
    cultural_note: "Andean and Amazonian cultures coexist; festivals often mix Catholic and Indigenous symbolism.",
    language_note: "Bolivian Spanish varies by altitude and region; Quechua and Aymara influence everyday vocabulary.",
    famous_for: "Salar de Uyuni, Andean textiles, Lake Titicaca, Indigenous heritage",
    must_know_phrase: "¿Qué tal, pues? — How's it going, then? (friendly filler)",
  },
  CL: {
    capital: "Santiago", population: 19600000, region: "Americas", subregion: "South America",
    fun_facts: ["Chile spans nearly 4,300 km north to south.", "Atacama is one of the driest deserts on Earth.", "Easter Island (Rapa Nui) belongs to Chile.", "Chilean wine is internationally renowned.", "The country sits on a major earthquake zone."],
    cultural_note: "Chilean life balances Pacific coast, Andes mountains, and strong literary traditions from poets like Neruda.",
    language_note: "Chilean Spanish is fast, drops final consonants, and uses unique slang (modismos chilenos).",
    famous_for: "Wine, Andes, Atacama Desert, poetry, seafood",
    must_know_phrase: "¿Cachai? — You get it? / Know what I mean?",
  },
  CO: {
    capital: "Bogotá", population: 52000000, region: "Americas", subregion: "South America",
    fun_facts: ["Colombia has coasts on both the Pacific and Caribbean.", "It is the world's leading source of emeralds.", "Arepas are eaten in countless regional styles.", "Coffee culture is central to national identity.", "Bogotá sits over 2,600 meters above sea level."],
    cultural_note: "Regional identities are strong — Caribbean costeño energy differs from Andean formality and Paisa warmth.",
    language_note: "Colombian Spanish is often called clear; Bogotá speech is relatively neutral, while coasts are faster and more melodic.",
    famous_for: "Coffee, emeralds, salsa in Cali, biodiversity, arepas",
    must_know_phrase: "¿Qué más? — What's up? (very common greeting)",
  },
  CR: {
    capital: "San José", population: 5200000, region: "Americas", subregion: "Central America",
    fun_facts: ["Costa Rica has no standing army since 1949.", "It hosts about 5% of world's biodiversity.", "Pura vida is a national philosophy and greeting.", "Ecotourism is a major industry.", "The country runs largely on renewable electricity."],
    cultural_note: "Costa Ricans (ticos) emphasize nature, calm living, and hospitality.",
    language_note: "Costa Rican Spanish uses usted more often even among friends in some contexts; pura vida appears everywhere.",
    famous_for: "Rainforests, beaches, coffee, pura vida, volcanoes",
    must_know_phrase: "Pura vida — Pure life / all good (greeting or farewell)",
  },
  CU: {
    capital: "Havana", population: 11000000, region: "Americas", subregion: "Caribbean",
    fun_facts: ["Classic American cars remain iconic street scenery.", "Cuban son and salsa shaped global music.", "The island has a world-famous ballet tradition.", "Dominoes is a beloved social pastime.", "Old Havana is a UNESCO World Heritage site."],
    cultural_note: "Music, humor, and neighborhood life animate Cuban culture despite economic constraints.",
    language_note: "Cuban Spanish swallows consonants (especially final s) and uses Caribbean vocabulary and rhythm.",
    famous_for: "Salsa, cigars, classic cars, rum, Havana architecture",
    must_know_phrase: "¿Qué bolá? — What's up? (informal Cuban greeting)",
  },
  DO: {
    capital: "Santo Domingo", population: 11300000, region: "Americas", subregion: "Caribbean",
    fun_facts: ["Santo Domingo is the oldest European city in the Americas.", "Merengue and bachata were born here.", "Baseball is a national passion.", "The island of Hispaniola is shared with Haiti.", "Dominican beaches draw major tourism."],
    cultural_note: "Family gatherings, dancing, and loud joyful conversation define much of Dominican social life.",
    language_note: "Dominican Spanish is rapid Caribbean speech; speakers often drop s and use distinctive slang.",
    famous_for: "Merengue, bachata, baseball, beaches, Colonial Zone",
    must_know_phrase: "¿Qué lo que? — What's up? (Dominican slang)",
  },
  EC: {
    capital: "Quito", population: 18000000, region: "Americas", subregion: "South America",
    fun_facts: ["The equator crosses Ecuador — the name means 'equator.'", "The Galápagos Islands belong to Ecuador.", "Quito's historic center is a UNESCO site.", "Ceviche and encebollado are coastal favorites.", "Andean markets sell colorful textiles."],
    cultural_note: "Coast, Andes, and Amazon create distinct Ecuadorian lifestyles and cuisines.",
    language_note: "Highland Spanish is relatively clear; coastal speech is faster. Kichwa influences some local words.",
    famous_for: "Galápagos, equator, Panama hats (toquilla), Andean markets",
    must_know_phrase: "¿De ley? — Really? / For sure?",
  },
  SV: {
    capital: "San Salvador", population: 6300000, region: "Americas", subregion: "Central America",
    fun_facts: ["Pupusas are the national dish.", "The country is nicknamed the Land of Volcanoes.", "Surf beaches on the Pacific are world-class.", "Indigo dye was historically important.", "Nahuatl heritage appears in place names."],
    cultural_note: "Salvadoran hospitality centers on family meals, pupuserías, and community festivals.",
    language_note: "Salvadoran Spanish uses voseo and Central American slang; speech can be quick and clipped.",
    famous_for: "Pupusas, volcanoes, Pacific surf, coffee",
    must_know_phrase: "¿Va pues? — Alright then? / Deal?",
  },
  GQ: {
    capital: "Malabo", population: 1700000, region: "Africa", subregion: "Middle Africa",
    fun_facts: ["The only African country with Spanish as an official language.", "It includes mainland Río Muni and Bioko island.", "Oil wealth transformed the economy in recent decades.", "French and Portuguese are also official.", "Traditional Fang culture remains influential."],
    cultural_note: "Equatorial Guinea blends Bantu traditions with Hispanic colonial history and Central African rhythms.",
    language_note: "Spanish coexists with Fang and other languages; local Spanish has African contact features. French is also widely present.",
    famous_for: "Spanish-speaking Africa, Bioko, oil, Fang culture",
    must_know_phrase: "¿Cómo estás, mi hermano? — How are you, my brother? (warm address)",
  },
  GT: {
    capital: "Guatemala City", population: 17600000, region: "Americas", subregion: "Central America",
    fun_facts: ["Antigua Guatemala is famous for colonial churches and volcanoes.", "Mayan languages remain widely spoken.", "Jade was prized in ancient Maya culture.", "The country produces excellent coffee and cardamom.", "Colorful woven textiles signal community identity."],
    cultural_note: "Maya heritage, Catholic festivals, and highland markets shape Guatemalan cultural life.",
    language_note: "Spanish is official, but many speak K'iche', Q'eqchi', and other Mayan languages. Guatemalan Spanish uses vos.",
    famous_for: "Maya ruins, Antigua, textiles, coffee, volcanoes",
    must_know_phrase: "¿Cómo está la situación? — How are things? (common check-in)",
  },
  HN: {
    capital: "Tegucigalpa", population: 10500000, region: "Americas", subregion: "Central America",
    fun_facts: ["Copán is a major Maya archaeological site.", "The Bay Islands are a scuba diving hotspot.", "Baleadas are a beloved street food.", "Garifuna culture thrives on the Caribbean coast.", "Pine forests cover much of the highlands."],
    cultural_note: "Honduran culture mixes Indigenous, European, and Afro-Caribbean Garifuna traditions.",
    language_note: "Honduran Spanish uses voseo; coastal speech includes Garifuna and Caribbean influences.",
    famous_for: "Copán ruins, Bay Islands, baleadas, Garifuna music",
    must_know_phrase: "¿Todo tranquilo? — Everything calm / all good?",
  },
  MX: {
    capital: "Mexico City", population: 129000000, region: "Americas", subregion: "North America",
    fun_facts: ["Mexico City was built on the Aztec capital Tenochtitlán.", "Mexican cuisine is UNESCO-listed intangible heritage.", "The country has 68+ national languages.", "Día de Muertos honors ancestors with ofrendas.", "Mexico is a global leader in silver production."],
    cultural_note: "From mariachi to mole, Mexican culture is regional, festive, and deeply tied to Indigenous and colonial history.",
    language_note: "Mexican Spanish is widely understood in media; it uses many Indigenous loanwords (chocolate, tomate, coyote).",
    famous_for: "Cuisine, Día de Muertos, beaches, pyramids, mariachi",
    must_know_phrase: "¿Qué onda? — What's up?",
  },
  NI: {
    capital: "Managua", population: 6900000, region: "Americas", subregion: "Central America",
    fun_facts: ["Nicaragua is called the land of lakes and volcanoes.", "Lake Nicaragua has islands and even freshwater sharks historically.", "Rubén Darío pioneered modernismo poetry.", "Gallo pinto is a daily staple.", "Colonial Granada is a major tourism draw."],
    cultural_note: "Poetry, volcano landscapes, and warm informal social life define much of Nicaraguan identity.",
    language_note: "Nicaraguan Spanish uses voseo extensively and has colorful local slang (nica).",
    famous_for: "Volcanoes, lakes, Granada, poetry, gallo pinto",
    must_know_phrase: "¿Cómo te va, vos? — How's it going? (using vos)",
  },
  PA: {
    capital: "Panama City", population: 4400000, region: "Americas", subregion: "Central America",
    fun_facts: ["The Panama Canal links the Atlantic and Pacific.", "The country uses the balboa and US dollar.", "Biodiversity corridors connect two continents.", "Pollera dresses feature in national festivals.", "Casco Viejo is a restored historic district."],
    cultural_note: "Panama's crossroads identity mixes Afro-Caribbean, Indigenous, and Latin American influences.",
    language_note: "Panamanian Spanish has Caribbean rhythm; English appears in canal-zone and tourism contexts.",
    famous_for: "Panama Canal, biodiversity, skyscrapers, beaches",
    must_know_phrase: "¿Qué xopá? — What's up? (Panamanian slang)",
  },
  PY: {
    capital: "Asunción", population: 6800000, region: "Americas", subregion: "South America",
    fun_facts: ["Guaraní is co-official with Spanish.", "Most Paraguayans are bilingual to some degree.", "Tereré (cold yerba mate) is a national ritual.", "The country is landlocked between Brazil, Argentina, and Bolivia.", "Ñandutí lace is a traditional craft."],
    cultural_note: "Paraguayan culture is famously bilingual and communal; sharing tereré signals friendship.",
    language_note: "Jopara mixes Spanish and Guaraní in daily speech — a hallmark of Paraguayan communication.",
    famous_for: "Guaraní language, tereré, Ñandutí lace, harp music",
    must_know_phrase: "Mba'éichapa — How are you? (Guaraní greeting used widely)",
  },
  PE: {
    capital: "Lima", population: 34000000, region: "Americas", subregion: "South America",
    fun_facts: ["Machu Picchu is a global icon of Inca engineering.", "Peru has dozens of potato varieties.", "Ceviche is a national culinary emblem.", "Quechua and Aymara remain widely spoken.", "The Nazca Lines are visible from the air."],
    cultural_note: "Peru layers Inca, Spanish colonial, and Amazonian cultures into world-class cuisine and festivals.",
    language_note: "Coastal Limeño Spanish is relatively clear; Andean Spanish shows Quechua influence in rhythm and lexicon.",
    famous_for: "Machu Picchu, ceviche, Andes, potatoes, Inca heritage",
    must_know_phrase: "¿Habla? — You there? / You listening? (casual check-in)",
  },
  PR: {
    capital: "San Juan", population: 3200000, region: "Americas", subregion: "Caribbean",
    fun_facts: ["Puerto Rico is a US territory with Spanish as the dominant language.", "Reggaetón has deep Puerto Rican roots.", "Old San Juan features brightly colored colonial streets.", "Coquí frogs are a national symbol.", "Pernil and mofongo are beloved dishes."],
    cultural_note: "Puerto Rican culture mixes Taíno, African, and Spanish heritage with strong US ties.",
    language_note: "Puerto Rican Spanish is Caribbean: rapid, often drops s, and freely code-switches with English.",
    famous_for: "Reggaetón, Old San Juan, beaches, coquí, cuisine",
    must_know_phrase: "¿Qué es la que hay? — What's going on?",
  },
  ES: {
    capital: "Madrid", population: 48000000, region: "Europe", subregion: "Southern Europe",
    fun_facts: ["Spanish is the world's second-most spoken native language overall.", "Spain has co-official languages like Catalan, Basque, and Galician.", "La Tomatina and Running of the Bulls are famous festivals.", "Tapas culture encourages sharing small plates.", "The country has more UNESCO World Heritage sites than most nations."],
    cultural_note: "Regional identities (Andalusia, Catalonia, Basque Country, Galicia) are as important as national ones.",
    language_note: "Peninsular Spanish distinguishes z/c from s (distinción) in much of the north/center; southern accents vary widely.",
    famous_for: "Tapas, flamenco, Prado, football, regional languages",
    must_know_phrase: "¿Qué tal? — How's it going?",
  },
  UY: {
    capital: "Montevideo", population: 3400000, region: "Americas", subregion: "South America",
    fun_facts: ["Uruguay legalized same-sex marriage early in the region.", "Mate is drunk constantly from a shared gourd.", "Carnival in Uruguay is among the world's longest.", "The country is a major beef and wool exporter.", "Soccer rivals Argentina in Río de la Plata passion."],
    cultural_note: "Uruguayans (charrúas/orientales) value social democracy, beach life, and mate circles.",
    language_note: "Like Argentina, Uruguay uses Rioplatense Spanish with voseo and sheísmo/zheísmo.",
    famous_for: "Mate, beaches, Carnival, beef, tango culture",
    must_know_phrase: "¿Todo bien, bo? — All good, friend? (bo = colloquial address)",
  },
  VE: {
    capital: "Caracas", population: 28300000, region: "Americas", subregion: "South America",
    fun_facts: ["Angel Falls is the world's highest uninterrupted waterfall.", "Arepa culture is central to daily meals.", "The country has Caribbean coastline and Andean peaks.", "Oil reserves are among the world's largest.", "Joropo is a traditional music and dance of the plains."],
    cultural_note: "Venezuelan culture is warm, musical, and regionally diverse from Caribbean coast to Los Llanos.",
    language_note: "Venezuelan Spanish is Caribbean-influenced: melodic, fast, and full of diminutives.",
    famous_for: "Angel Falls, arepas, oil, Caribbean coast, joropo",
    must_know_phrase: "¿Qué más, vale? — What's up, buddy?",
  },
};

const FR_FACTS: Record<string, CountryFacts> = {
  BE: {
    capital: "Brussels", population: 11700000, region: "Europe", subregion: "Western Europe",
    fun_facts: ["Belgium has three official languages: Dutch, French, German.", "Brussels hosts major EU institutions.", "Belgian fries and chocolate are world-famous.", "Comic art (Tintin, Smurfs) is a national pride.", "The country is known for hundreds of beers."],
    cultural_note: "Belgian identity balances Flemish and Francophone cultures with a love of food and festivals.",
    language_note: "Belgian French uses some unique words (septante, nonante) instead of soixante-dix / quatre-vingt-dix.",
    famous_for: "Chocolate, beer, fries, comics, EU capital",
    must_know_phrase: "Une fois — discourse particle adding emphasis (Belgian French)",
  },
  CM: {
    capital: "Yaoundé", population: 28000000, region: "Africa", subregion: "Middle Africa",
    fun_facts: ["Cameroon is called Africa in miniature for its diversity.", "French and English are both official.", "Indomitable Lions football team has a huge following.", "Over 200 languages are spoken.", "Makossa and bikutsi are popular music styles."],
    cultural_note: "Cameroonian culture is fiercely regional — coastal, highland, and northern traditions differ widely.",
    language_note: "Cameroonian French is widely used in media and cities, with local vocabulary and rhythmic speech.",
    famous_for: "Football, cultural diversity, music, national parks",
    must_know_phrase: "On est ensemble — We're in this together / solidarity phrase",
  },
  CA: {
    capital: "Ottawa", population: 40000000, region: "Americas", subregion: "North America",
    fun_facts: ["Canada is officially bilingual (English/French).", "Québec is the heart of North American French.", "Poutine was invented in Québec.", "Winter festivals celebrate ice and snow culture.", "Maple syrup is a national emblem."],
    cultural_note: "Francophone Canada centers on Québec but also Acadia and other communities with distinct traditions.",
    language_note: "Québécois French has unique vowels, vocabulary (char, magasinage), and informal tu usage.",
    famous_for: "Maple syrup, poutine, Québec City, winter sports, bilingualism",
    must_know_phrase: "Ça va-tu bien? — Going well? (Québécois interrogative -tu)",
  },
  CG: {
    capital: "Brazzaville", population: 6100000, region: "Africa", subregion: "Middle Africa",
    fun_facts: ["Brazzaville faces Kinshasa across the Congo River.", "French is the official language.", "The country has Atlantic rainforest and savanna.", "Rumba and soukous influences cross the river.", "It is often called Congo-Brazzaville."],
    cultural_note: "Congolese culture prizes music, dance, and extended family networks.",
    language_note: "French is used in administration; Lingala and Kituba are important lingua francas.",
    famous_for: "Congo River, rumba influences, rainforests, Brazzaville",
    must_know_phrase: "Merci mingi — Thank you a lot (French + Lingala contact phrase)",
  },
  CD: {
    capital: "Kinshasa", population: 102000000, region: "Africa", subregion: "Middle Africa",
    fun_facts: ["DR Congo is one of Africa's largest countries.", "Kinshasa is a major Francophone megacity.", "Congolese rumba is UNESCO-recognized.", "The Congo Basin holds vast rainforests.", "Over 200 languages are spoken nationally."],
    cultural_note: "Music, fashion (sapeurs), and vibrant urban culture make Kinshasa a cultural powerhouse.",
    language_note: "French is official; Lingala dominates Kinshasa street speech and music lyrics.",
    famous_for: "Congolese rumba, Congo Basin, Kinshasa, minerals",
    must_know_phrase: "Bolingo — Love (Lingala word often heard in songs/French mix)",
  },
  BJ: {
    capital: "Porto-Novo", population: 13700000, region: "Africa", subregion: "Western Africa",
    fun_facts: ["Benin is the cradle of Vodun (Voodoo) traditions.", "French is the official language.", "The Gateway of No Return memorializes the slave trade.", "Ganvie is a famous stilt village on a lagoon.", "Football and music are popular pastimes."],
    cultural_note: "Beninese culture blends Vodun spirituality, markets, and Francophone education.",
    language_note: "French is used in schools and government; Fon and Yoruba are widely spoken at home.",
    famous_for: "Vodun, Ouidah history, markets, stilt villages",
    must_know_phrase: "Bonjour, comment ça va ? — Hello, how are you? (essential formal start)",
  },
  GQ: {
    capital: "Malabo", population: 1700000, region: "Africa", subregion: "Middle Africa",
    fun_facts: ["French is one of three official European languages here.", "The country sits between Gabon and Cameroon.", "Oil exports dominate the modern economy.", "Spanish remains historically prominent.", "Bioko island hosts the capital Malabo."],
    cultural_note: "Equatorial Guinea's Francophone ties sit alongside Hispanic and Fang cultural roots.",
    language_note: "French is used administratively alongside Spanish; local languages remain strong in daily life.",
    famous_for: "Bilingual Africa, oil, Bioko, Fang heritage",
    must_know_phrase: "On se débrouille — We manage / we make do",
  },
  FR: {
    capital: "Paris", population: 68000000, region: "Europe", subregion: "Western Europe",
    fun_facts: ["French is spoken on five continents.", "France has the most time zones of any country (including overseas).", "The Louvre is the world's most-visited museum.", "TGV high-speed trains reshape travel.", "French gastronomy is UNESCO-listed."],
    cultural_note: "Café life, regional cuisines, and strong arts institutions define everyday French culture.",
    language_note: "Metropolitan French is the media standard; regional accents (Midi, North, Alsace) still vary.",
    famous_for: "Cuisine, wine, fashion, Louvre, countryside",
    must_know_phrase: "Ça va ? — How's it going? / You good?",
  },
  GA: {
    capital: "Libreville", population: 2400000, region: "Africa", subregion: "Middle Africa",
    fun_facts: ["About 80%+ of Gabon is covered by forest.", "French is the official language.", "Loango and Ivindo parks protect rare wildlife.", "Libreville means 'free town.'", "Oil and timber shape the economy."],
    cultural_note: "Gabonese culture values forest traditions, urban Francophone life, and music.",
    language_note: "French dominates public life; Fang and other languages are used communally.",
    famous_for: "Rainforests, wildlife parks, Libreville, oil",
    must_know_phrase: "On est là — We're here / present (solidarity vibe)",
  },
  GN: {
    capital: "Conakry", population: 14100000, region: "Africa", subregion: "Western Africa",
    fun_facts: ["Guinea has major bauxite reserves.", "French is official after independence from France.", "The country has Atlantic coastline and Fouta Djallon highlands.", "Djembe drumming traditions are influential.", "Conakry is a peninsula capital."],
    cultural_note: "Music, Islamic and traditional festivals, and market life animate Guinean culture.",
    language_note: "French is administrative; Pular, Maninka, and Susu are major national languages.",
    famous_for: "Djembe traditions, bauxite, Fouta Djallon, Conakry",
    must_know_phrase: "Ça dit quoi ? — What's up? (informal Francophone Africa)",
  },
  HT: {
    capital: "Port-au-Prince", population: 11700000, region: "Americas", subregion: "Caribbean",
    fun_facts: ["Haiti was the first Black republic after a successful slave revolt.", "French and Haitian Creole are official.", "Kompa music is a national sound.", "Vibrant painting traditions are world-known.", "The Citadelle Laferrière is a monumental fortress."],
    cultural_note: "Haitian culture is resilient, creative, and rooted in Creole language, Vodou heritage, and community solidarity.",
    language_note: "French appears in formal contexts; Haitian Creole is the mother tongue of most people.",
    famous_for: "Revolution history, Creole, kompa, art, Citadelle",
    must_know_phrase: "Sak pase? — What's happening? (Creole greeting often heard)",
  },
  CI: {
    capital: "Yamoussoukro (official) / Abidjan (economic)", population: 29000000, region: "Africa", subregion: "Western Africa",
    fun_facts: ["Côte d'Ivoire is a top cocoa producer.", "Abidjan is a major Francophone business hub.", "Coupé-décalé and zouglou are popular music styles.", "French is the official language.", "The Basilica of Yamoussoukro is enormous."],
    cultural_note: "Ivorian culture mixes over 60 ethnic groups with a stylish urban Abidjan scene.",
    language_note: "Ivorian French includes local slang (nouchi) widely used by youth in Abidjan.",
    famous_for: "Cocoa, Abidjan, music, beaches, basilica",
    must_know_phrase: "On est ensemble — We're together (common solidarity phrase)",
  },
  LU: {
    capital: "Luxembourg City", population: 660000, region: "Europe", subregion: "Western Europe",
    fun_facts: ["Luxembourgish, French, and German are all used officially.", "The country has the highest GDP per capita in the EU.", "French dominates written administration and law.", "The old city is a UNESCO site.", "Cross-border workers flood in daily."],
    cultural_note: "Luxembourg's culture is multilingual and cosmopolitan while retaining local festivals.",
    language_note: "French is common in business and shops; locals often switch languages mid-conversation.",
    famous_for: "Finance, castles, multilingualism, old city",
    must_know_phrase: "Bonjour, s'il vous plaît — Hello, please (polite service French)",
  },
  MG: {
    capital: "Antananarivo", population: 30000000, region: "Africa", subregion: "Eastern Africa",
    fun_facts: ["Madagascar is the world's fourth-largest island.", "Lemurs exist naturally only here.", "French and Malagasy are official.", "Vanilla and spices are key exports.", "The avenue of the Baobabs is iconic."],
    cultural_note: "Malagasy culture emphasizes ancestry, music, and regional kingdoms' heritage.",
    language_note: "French is used in education and media; Malagasy is the everyday mother tongue.",
    famous_for: "Lemurs, baobabs, vanilla, biodiversity",
    must_know_phrase: "Manao ahoana — Hello (Malagasy greeting used alongside French)",
  },
  ML: {
    capital: "Bamako", population: 23000000, region: "Africa", subregion: "Western Africa",
    fun_facts: ["Timbuktu was a historic center of learning.", "Mali is a giant of West African music (kora, desert blues).", "French is official.", "The Niger River is a lifeline.", "Djenné's mud mosque is world-famous."],
    cultural_note: "Griots, music, and market culture make Mali a cultural reference for West Africa.",
    language_note: "French is official; Bambara is the most widely spoken lingua franca.",
    famous_for: "Timbuktu, desert blues, Djenné mosque, Niger River",
    must_know_phrase: "I ni ce — Thank you (Bambara; heard with French daily)",
  },
  MR: {
    capital: "Nouakchott", population: 4800000, region: "Africa", subregion: "Western Africa",
    fun_facts: ["Arabic is official; French remains widely used.", "Much of the country is Sahara Desert.", "The Banc d'Arguin is a major bird sanctuary.", "Mauritania bridges Maghreb and Sahel cultures.", "Tea ceremonies are an important social ritual."],
    cultural_note: "Hassaniya Arab and Sahelian traditions shape music, dress, and hospitality.",
    language_note: "French appears in business and education; Hassaniya Arabic dominates daily speech.",
    famous_for: "Sahara, Banc d'Arguin, tea culture, desert cities",
    must_know_phrase: "Salaam aleikum — Peace be upon you (common greeting)",
  },
  MC: {
    capital: "Monaco", population: 39000, region: "Europe", subregion: "Western Europe",
    fun_facts: ["Monaco is one of the world's smallest countries.", "French is the official language.", "The Formula 1 Monaco Grand Prix is legendary.", "The casino of Monte-Carlo is iconic.", "It is a densely populated microstate on the Riviera."],
    cultural_note: "Monégasque life mixes French Riviera glamour with local princely traditions.",
    language_note: "French is everyday language; Monégasque (a Ligurian variety) is promoted culturally.",
    famous_for: "Grand Prix, casino, yachts, Riviera luxury",
    must_know_phrase: "Enchanté(e) — Nice to meet you",
  },
  NE: {
    capital: "Niamey", population: 27000000, region: "Africa", subregion: "Western Africa",
    fun_facts: ["Niger is named after the Niger River.", "French is the official language.", "Much of the north is Sahara.", "Traditional wrestling is popular.", "The country has rich Hausa and Tuareg cultures."],
    cultural_note: "Nigerien culture features desert heritage, markets, and strong oral traditions.",
    language_note: "French is used officially; Hausa and Zarma are major spoken languages.",
    famous_for: "Niger River, Sahara, wrestling, Tuareg culture",
    must_know_phrase: "Fofo — Hello/hi (Zarma; used with French in Niamey)",
  },
  RW: {
    capital: "Kigali", population: 14000000, region: "Africa", subregion: "Eastern Africa",
    fun_facts: ["Rwanda has four official languages including French and English.", "It is called the Land of a Thousand Hills.", "Plastic bags are banned nationally.", "Gorilla trekking is a major attraction.", "Kigali is known for cleanliness and order."],
    cultural_note: "Rwandan culture emphasizes community, dance (intore), and post-genocide reconciliation narratives.",
    language_note: "French remains in use, though English and Kinyarwanda are very prominent in public life.",
    famous_for: "Hills, mountain gorillas, Kigali, cleanliness campaigns",
    must_know_phrase: "Muraho — Hello (Kinyarwanda greeting used nationwide)",
  },
  SN: {
    capital: "Dakar", population: 18000000, region: "Africa", subregion: "Western Africa",
    fun_facts: ["French is official; Wolof dominates daily conversation.", "Dakar hosts the finish of the famous rally (historically).", "Teranga means legendary hospitality.", "Youssou N'Dour popularized mbalax globally.", "Gorée Island memorializes the slave trade."],
    cultural_note: "Senegalese teranga (hospitality), music, and café Touba culture welcome visitors warmly.",
    language_note: "Senegalese French is widely spoken in cities; Wolof phrases mix freely into French speech.",
    famous_for: "Teranga, mbalax, Dakar, Gorée, wrestling",
    must_know_phrase: "Nanga def ? — How are you? (Wolof; used constantly with French)",
  },
  CH: {
    capital: "Bern", population: 8900000, region: "Europe", subregion: "Western Europe",
    fun_facts: ["Switzerland has four national languages including French.", "Romandy is the French-speaking region.", "Swiss neutrality is a long tradition.", "Chocolate and watches are signature exports.", "Direct democracy uses frequent referendums."],
    cultural_note: "Swiss French culture mixes Alpine traditions with precise public life and café society in Geneva/Lausanne.",
    language_note: "Swiss French uses septante/nonante and some local terms; accents are generally clear.",
    famous_for: "Alps, chocolate, watches, banks, lakes",
    must_know_phrase: "Ça joue ? — Does that work? / All good? (Swiss casual)",
  },
  TG: {
    capital: "Lomé", population: 9000000, region: "Africa", subregion: "Western Africa",
    fun_facts: ["Togo is a narrow country on the Gulf of Guinea.", "French is the official language.", "Lomé's Grand Marché is famous.", "Traditional fetish markets attract cultural tourism.", "Football is widely followed."],
    cultural_note: "Togolese culture features coastal markets, Ewe traditions, and Francophone urban life.",
    language_note: "French is official; Éwé and Kabiyé are major national languages.",
    famous_for: "Lomé markets, beaches, traditional culture, football",
    must_know_phrase: "Yovo — term for foreigner (heard often; learn it respectfully)",
  },
  BF: {
    capital: "Ouagadougou", population: 23000000, region: "Africa", subregion: "Western Africa",
    fun_facts: ["Burkina Faso means 'land of upright people.'", "FESPACO is Africa's major film festival (Ouaga).", "French is official.", "The country is known for bronze sculptures and masks.", "Sahelian climate shapes daily life."],
    cultural_note: "Burkinabè arts — film, masks, and music — punch far above the country's size.",
    language_note: "French is used in administration; Moore and Dioula are widely spoken.",
    famous_for: "FESPACO film festival, masks, crafts, Sahel culture",
    must_know_phrase: "Laapassé — Informal 'hi/what's up' vibe in local French youth speech",
  },
};

export function getCountryFacts(alpha2: string, language: Lang): CountryFacts | null {
  const code = alpha2.trim().toUpperCase();
  const bank = language === "fr" ? FR_FACTS : ES_FACTS;
  return bank[code] ?? null;
}
