export type SentenceExercise = {
  english: string;
  target: string;
  words: string[];
  distractors: string[];
  hint: string;
  topic?: string;
  cefrLevel: string;
  language: "es" | "fr";
};

export type PickedSentence = SentenceExercise & { allWords: string[] };

function fisherYates<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j]!, a[i]!];
  }
  return a;
}

function levelKey(cefrLevel: string): string {
  const L = (cefrLevel || "A1").toUpperCase();
  if (L === "A1" || L === "A2" || L === "B1") return L;
  // B2+ reuse B1 pool
  return "B1";
}

const EXERCISES: SentenceExercise[] = [
  { english: "I drink water every day.", target: "Bebo agua todos los días.", words: ["Bebo", "agua", "todos", "los", "días."], distractors: ["come", "mucho", "una", "siempre"], hint: "Present tense: bebo = I drink.", topic: "Daily Life", cefrLevel: "A1", language: "es" },
  { english: "She opens the window.", target: "Ella abre la ventana.", words: ["Ella", "abre", "la", "ventana."], distractors: ["abreis", "el", "puerta", "cierran"], hint: "abre agrees with ella.", topic: "Daily Life", cefrLevel: "A1", language: "es" },
  { english: "We live in a small house.", target: "Vivimos en una casa pequeña.", words: ["Vivimos", "en", "una", "casa", "pequeña."], distractors: ["vivo", "grande", "el", "casas"], hint: "vivimos = we live.", topic: "Daily Life", cefrLevel: "A1", language: "es" },
  { english: "They wash the dishes.", target: "Ellos lavan los platos.", words: ["Ellos", "lavan", "los", "platos."], distractors: ["lava", "las", "plato", "comemos"], hint: "lavan is they-form.", topic: "Daily Life", cefrLevel: "A1", language: "es" },
  { english: "I usually wake up at seven.", target: "Normalmente me levanto a las siete.", words: ["Normalmente", "me", "levanto", "a", "las", "siete."], distractors: ["levantas", "el", "ocho", "despiertas"], hint: "Reflexive: me levanto.", topic: "Daily Life", cefrLevel: "A2", language: "es" },
  { english: "Can you help me today?", target: "¿Puedes ayudarme hoy?", words: ["¿Puedes", "ayudarme", "hoy?"], distractors: ["puedo", "ayudarte", "mañana", "pueden"], hint: "Infinitive attaches: ayudarme.", topic: "Daily Life", cefrLevel: "A2", language: "es" },
  { english: "We need to buy bread.", target: "Necesitamos comprar pan.", words: ["Necesitamos", "comprar", "pan."], distractors: ["necesito", "compramos", "leche", "panes"], hint: "necesitar + infinitive.", topic: "Daily Life", cefrLevel: "A2", language: "es" },
  { english: "The store closes at nine.", target: "La tienda cierra a las nueve.", words: ["La", "tienda", "cierra", "a", "las", "nueve."], distractors: ["cierran", "abre", "el", "ocho"], hint: "cierra = it closes.", topic: "Daily Life", cefrLevel: "A2", language: "es" },
  { english: "I have already finished my homework.", target: "Ya he terminado mi tarea.", words: ["Ya", "he", "terminado", "mi", "tarea."], distractors: ["has", "terminé", "su", "deberes"], hint: "Present perfect: he + participle.", topic: "Daily Life", cefrLevel: "B1", language: "es" },
  { english: "If it rains, I stay home.", target: "Si llueve, me quedo en casa.", words: ["Si", "llueve,", "me", "quedo", "en", "casa."], distractors: ["llover", "quedas", "la", "llovió"], hint: "Real conditional with present.", topic: "Daily Life", cefrLevel: "B1", language: "es" },
  { english: "She asked me to wait a moment.", target: "Ella me pidió que esperara un momento.", words: ["Ella", "me", "pidió", "que", "esperara", "un", "momento."], distractors: ["pidióme", "espere", "una", "pedir"], hint: "Past + subjunctive clause.", topic: "Daily Life", cefrLevel: "B1", language: "es" },
  { english: "We used to walk after dinner.", target: "Solíamos caminar después de la cena.", words: ["Solíamos", "caminar", "después", "de", "la", "cena."], distractors: ["solía", "caminamos", "antes", "el"], hint: "soler in imperfect = used to.", topic: "Daily Life", cefrLevel: "B1", language: "es" },
  { english: "Where is the hotel?", target: "¿Dónde está el hotel?", words: ["¿Dónde", "está", "el", "hotel?"], distractors: ["estoy", "la", "aeropuerto", "son"], hint: "está for location.", topic: "Travel", cefrLevel: "A1", language: "es" },
  { english: "I need a ticket.", target: "Necesito un boleto.", words: ["Necesito", "un", "boleto."], distractors: ["necesitas", "una", "billete", "quiero"], hint: "un + masculine noun.", topic: "Travel", cefrLevel: "A1", language: "es" },
  { english: "The train is late.", target: "El tren llega tarde.", words: ["El", "tren", "llega", "tarde."], distractors: ["llegó", "la", "avión", "temprano"], hint: "llega = arrives.", topic: "Travel", cefrLevel: "A1", language: "es" },
  { english: "We go to the airport.", target: "Vamos al aeropuerto.", words: ["Vamos", "al", "aeropuerto."], distractors: ["voy", "a", "la", "estación"], hint: "al = a + el.", topic: "Travel", cefrLevel: "A1", language: "es" },
  { english: "How do I get to the museum?", target: "¿Cómo llego al museo?", words: ["¿Cómo", "llego", "al", "museo?"], distractors: ["llegas", "a", "la", "teatro"], hint: "llegar a = arrive/get to.", topic: "Travel", cefrLevel: "A2", language: "es" },
  { english: "Please show me the map.", target: "Por favor, muéstrame el mapa.", words: ["Por", "favor,", "muéstrame", "el", "mapa."], distractors: ["muestra", "la", "mapas", "enséñanos"], hint: "Affirmative tú command: mostrar → muestra → muéstrame.", topic: "Travel", cefrLevel: "A2", language: "es" },
  { english: "Our flight leaves at noon.", target: "Nuestro vuelo sale al mediodía.", words: ["Nuestro", "vuelo", "sale", "al", "mediodía."], distractors: ["nuestra", "salen", "la", "noche"], hint: "sale = leaves.", topic: "Travel", cefrLevel: "A2", language: "es" },
  { english: "I lost my suitcase yesterday.", target: "Ayer perdí mi maleta.", words: ["Ayer", "perdí", "mi", "maleta."], distractors: ["perdiste", "su", "maletas", "pierdo"], hint: "Preterite: perdí.", topic: "Travel", cefrLevel: "A2", language: "es" },
  { english: "I wish the bus would come soon.", target: "Ojalá venga pronto el autobús.", words: ["Ojalá", "venga", "pronto", "el", "autobús."], distractors: ["viene", "vengaos", "la", "tren"], hint: "ojalá + subjunctive.", topic: "Travel", cefrLevel: "B1", language: "es" },
  { english: "By the time we arrived, the gate had closed.", target: "Cuando llegamos, la puerta ya se había cerrado.", words: ["Cuando", "llegamos,", "la", "puerta", "ya", "se", "había", "cerrado."], distractors: ["llegábamos", "habían", "el", "abre"], hint: "Past perfect: había cerrado.", topic: "Travel", cefrLevel: "B1", language: "es" },
  { english: "Could you tell me which platform it is?", target: "¿Podría decirme qué andén es?", words: ["¿Podría", "decirme", "qué", "andén", "es?"], distractors: ["puedes", "decir", "cuál", "estación"], hint: "Podría is polite.", topic: "Travel", cefrLevel: "B1", language: "es" },
  { english: "We should reserve seats in advance.", target: "Deberíamos reservar asientos con antelación.", words: ["Deberíamos", "reservar", "asientos", "con", "antelación."], distractors: ["debemos", "reserva", "asiento", "antes"], hint: "Conditional of deber.", topic: "Travel", cefrLevel: "B1", language: "es" },
  { english: "I like rice.", target: "Me gusta el arroz.", words: ["Me", "gusta", "el", "arroz."], distractors: ["gustan", "la", "pan", "quiero"], hint: "gusta with singular noun.", topic: "Food", cefrLevel: "A1", language: "es" },
  { english: "She eats fruit.", target: "Ella come fruta.", words: ["Ella", "come", "fruta."], distractors: ["comes", "comemos", "verdura", "bebé"], hint: "come = she eats.", topic: "Food", cefrLevel: "A1", language: "es" },
  { english: "The soup is hot.", target: "La sopa está caliente.", words: ["La", "sopa", "está", "caliente."], distractors: ["es", "el", "fría", "están"], hint: "está for temporary state.", topic: "Food", cefrLevel: "A1", language: "es" },
  { english: "We want coffee.", target: "Queremos café.", words: ["Queremos", "café."], distractors: ["quiero", "agua", "queréis", "té"], hint: "queremos = we want.", topic: "Food", cefrLevel: "A1", language: "es" },
  { english: "This restaurant serves spicy food.", target: "Este restaurante sirve comida picante.", words: ["Este", "restaurante", "sirve", "comida", "picante."], distractors: ["sirven", "esta", "plato", "dulce"], hint: "servir is stem-changing.", topic: "Food", cefrLevel: "A2", language: "es" },
  { english: "I prefer chicken without salt.", target: "Prefiero el pollo sin sal.", words: ["Prefiero", "el", "pollo", "sin", "sal."], distractors: ["prefieres", "la", "carne", "con"], hint: "preferir → prefiero.", topic: "Food", cefrLevel: "A2", language: "es" },
  { english: "Can we order dessert now?", target: "¿Podemos pedir el postre ahora?", words: ["¿Podemos", "pedir", "el", "postre", "ahora?"], distractors: ["puedo", "pedimos", "la", "luego"], hint: "poder + infinitive.", topic: "Food", cefrLevel: "A2", language: "es" },
  { english: "The market opens early on Sundays.", target: "El mercado abre temprano los domingos.", words: ["El", "mercado", "abre", "temprano", "los", "domingos."], distractors: ["abren", "la", "tarde", "lunes"], hint: "Habitual present.", topic: "Food", cefrLevel: "A2", language: "es" },
  { english: "I would try the dish if it weren't so spicy.", target: "Probaría el plato si no fuera tan picante.", words: ["Probaría", "el", "plato", "si", "no", "fuera", "tan", "picante."], distractors: ["probaré", "fuera", "la", "salado"], hint: "Conditional + imperfect subjunctive.", topic: "Food", cefrLevel: "B1", language: "es" },
  { english: "They say this cheese is made nearby.", target: "Dicen que este queso se elabora cerca.", words: ["Dicen", "que", "este", "queso", "se", "elabora", "cerca."], distractors: ["dice", "elaboran", "esa", "lejos"], hint: "se elabora = is made.", topic: "Food", cefrLevel: "B1", language: "es" },
  { english: "Before cooking, wash the vegetables well.", target: "Antes de cocinar, lava bien las verduras.", words: ["Antes", "de", "cocinar,", "lava", "bien", "las", "verduras."], distractors: ["lavas", "el", "cocinas", "fruta"], hint: "Infinitive after antes de.", topic: "Food", cefrLevel: "B1", language: "es" },
  { english: "I'm full, but the cake smells amazing.", target: "Estoy lleno, pero el pastel huele increíble.", words: ["Estoy", "lleno,", "pero", "el", "pastel", "huele", "increíble."], distractors: ["soy", "llena", "la", "sabe"], hint: "oler → huele.", topic: "Food", cefrLevel: "B1", language: "es" },
  { english: "The dog is big.", target: "El perro es grande.", words: ["El", "perro", "es", "grande."], distractors: ["está", "la", "gato", "pequeño"], hint: "ser for inherent quality.", topic: "Animals", cefrLevel: "A1", language: "es" },
  { english: "Cats drink milk.", target: "Los gatos beben leche.", words: ["Los", "gatos", "beben", "leche."], distractors: ["bebe", "las", "agua", "comen"], hint: "beben = they drink.", topic: "Animals", cefrLevel: "A1", language: "es" },
  { english: "I see a bird.", target: "Veo un pájaro.", words: ["Veo", "un", "pájaro."], distractors: ["ves", "una", "perro", "miro"], hint: "ver → veo.", topic: "Animals", cefrLevel: "A1", language: "es" },
  { english: "The fish swims fast.", target: "El pez nada rápido.", words: ["El", "pez", "nada", "rápido."], distractors: ["nadan", "la", "lento", "corre"], hint: "nada = swims.", topic: "Animals", cefrLevel: "A1", language: "es" },
  { english: "My horse runs in the field.", target: "Mi caballo corre en el campo.", words: ["Mi", "caballo", "corre", "en", "el", "campo."], distractors: ["corren", "la", "casa", "caballos"], hint: "correr regular.", topic: "Animals", cefrLevel: "A2", language: "es" },
  { english: "There are many sheep here.", target: "Hay muchas ovejas aquí.", words: ["Hay", "muchas", "ovejas", "aquí."], distractors: ["haber", "muchos", "oveja", "allí"], hint: "hay = there is/are.", topic: "Animals", cefrLevel: "A2", language: "es" },
  { english: "The baby elephant is cute.", target: "El elefante bebé es adorable.", words: ["El", "elefante", "bebé", "es", "adorable."], distractors: ["está", "la", "feo", "elefantes"], hint: "Noun-adjective agreement.", topic: "Animals", cefrLevel: "A2", language: "es" },
  { english: "Don't feed the animals.", target: "No alimentes a los animales.", words: ["No", "alimentes", "a", "los", "animales."], distractors: ["alimenta", "el", "das", "animale"], hint: "Negative tú command.", topic: "Animals", cefrLevel: "A2", language: "es" },
  { english: "If I had a dog, I would walk it daily.", target: "Si tuviera un perro, lo pasearía a diario.", words: ["Si", "tuviera", "un", "perro,", "lo", "pasearía", "a", "diario."], distractors: ["tengo", "paseo", "una", "siempre"], hint: "Contrary-to-fact conditional.", topic: "Animals", cefrLevel: "B1", language: "es" },
  { english: "Birds that migrate travel thousands of kilometers.", target: "Los pájaros que migran recorren miles de kilómetros.", words: ["Los", "pájaros", "que", "migran", "recorren", "miles", "de", "kilómetros."], distractors: ["migra", "recorre", "las", "metro"], hint: "Relative clause with que.", topic: "Animals", cefrLevel: "B1", language: "es" },
  { english: "She is afraid of spiders.", target: "Ella les tiene miedo a las arañas.", words: ["Ella", "les", "tiene", "miedo", "a", "las", "arañas."], distractors: ["le", "tenemos", "el", "araña"], hint: "tener miedo a.", topic: "Animals", cefrLevel: "B1", language: "es" },
  { english: "The zoo closed because the storm arrived.", target: "El zoológico cerró porque llegó la tormenta.", words: ["El", "zoológico", "cerró", "porque", "llegó", "la", "tormenta."], distractors: ["cierra", "llegaron", "el", "lluvia"], hint: "Preterite narrative.", topic: "Animals", cefrLevel: "B1", language: "es" },
  { english: "I work in an office.", target: "Trabajo en una oficina.", words: ["Trabajo", "en", "una", "oficina."], distractors: ["trabajas", "un", "escuela", "trabajo"], hint: "yo form ends in -o.", topic: "Work", cefrLevel: "A1", language: "es" },
  { english: "She is a teacher.", target: "Ella es profesora.", words: ["Ella", "es", "profesora."], distractors: ["está", "profesor", "son", "médica"], hint: "ser for profession.", topic: "Work", cefrLevel: "A1", language: "es" },
  { english: "We start at nine.", target: "Empezamos a las nueve.", words: ["Empezamos", "a", "las", "nueve."], distractors: ["empiezo", "el", "ocho", "terminamos"], hint: "empezar stem change in yo only for some forms.", topic: "Work", cefrLevel: "A1", language: "es" },
  { english: "He writes emails.", target: "Él escribe correos.", words: ["Él", "escribe", "correos."], distractors: ["escribo", "escribeis", "cartas", "lee"], hint: "escribir regular.", topic: "Work", cefrLevel: "A1", language: "es" },
  { english: "I have a meeting this afternoon.", target: "Tengo una reunión esta tarde.", words: ["Tengo", "una", "reunión", "esta", "tarde."], distractors: ["tiene", "un", "mañana", "tuvimos"], hint: "tener → tengo.", topic: "Work", cefrLevel: "A2", language: "es" },
  { english: "Could you send the file?", target: "¿Puedes enviar el archivo?", words: ["¿Puedes", "enviar", "el", "archivo?"], distractors: ["puedo", "envías", "la", "documento"], hint: "poder + infinitive.", topic: "Work", cefrLevel: "A2", language: "es" },
  { english: "My boss calls every Monday.", target: "Mi jefe llama todos los lunes.", words: ["Mi", "jefe", "llama", "todos", "los", "lunes."], distractors: ["llaman", "jefa", "cada", "martes"], hint: "Habitual present.", topic: "Work", cefrLevel: "A2", language: "es" },
  { english: "We finished the project yesterday.", target: "Terminamos el proyecto ayer.", words: ["Terminamos", "el", "proyecto", "ayer."], distractors: ["terminamos", "la", "hoy", "acabo"], hint: "Preterite nosotros looks like present.", topic: "Work", cefrLevel: "A2", language: "es" },
  { english: "I would accept the job if the salary were better.", target: "Aceptaría el trabajo si el sueldo fuera mejor.", words: ["Aceptaría", "el", "trabajo", "si", "el", "sueldo", "fuera", "mejor."], distractors: ["acepto", "sea", "la", "peor"], hint: "Conditional + imperfect subjunctive.", topic: "Work", cefrLevel: "B1", language: "es" },
  { english: "Please let me know when you arrive.", target: "Avísame cuando llegues.", words: ["Avísame", "cuando", "llegues."], distractors: ["avisa", "llegas", "llegar", "nos"], hint: "cuando + subjunctive for future.", topic: "Work", cefrLevel: "B1", language: "es" },
  { english: "She has been working here for two years.", target: "Lleva dos años trabajando aquí.", words: ["Lleva", "dos", "años", "trabajando", "aquí."], distractors: ["lleva", "trabajo", "tres", "allí"], hint: "llevar + time + gerund.", topic: "Work", cefrLevel: "B1", language: "es" },
  { english: "The report must be submitted today.", target: "El informe debe entregarse hoy.", words: ["El", "informe", "debe", "entregarse", "hoy."], distractors: ["deben", "entrega", "la", "mañana"], hint: "Infinitive + se for passive feel.", topic: "Work", cefrLevel: "B1", language: "es" },
  { english: "This is my mother.", target: "Esta es mi madre.", words: ["Esta", "es", "mi", "madre."], distractors: ["este", "está", "padre", "su"], hint: "esta agrees with madre.", topic: "Family", cefrLevel: "A1", language: "es" },
  { english: "I have two brothers.", target: "Tengo dos hermanos.", words: ["Tengo", "dos", "hermanos."], distractors: ["tiene", "dos", "hermanas", "hay"], hint: "hermanos can mean siblings.", topic: "Family", cefrLevel: "A1", language: "es" },
  { english: "Our grandmother is kind.", target: "Nuestra abuela es amable.", words: ["Nuestra", "abuela", "es", "amable."], distractors: ["nuestro", "está", "abuelo", "serio"], hint: "nuestra + feminine.", topic: "Family", cefrLevel: "A1", language: "es" },
  { english: "The baby sleeps now.", target: "El bebé duerme ahora.", words: ["El", "bebé", "duerme", "ahora."], distractors: ["duermen", "la", "luego", "come"], hint: "dormir → duerme.", topic: "Family", cefrLevel: "A1", language: "es" },
  { english: "My sister lives with her husband.", target: "Mi hermana vive con su esposo.", words: ["Mi", "hermana", "vive", "con", "su", "esposo."], distractors: ["viven", "hermano", "mi", "mujer"], hint: "su = his/her/their.", topic: "Family", cefrLevel: "A2", language: "es" },
  { english: "We visit our cousins on weekends.", target: "Visitamos a nuestros primos los fines de semana.", words: ["Visitamos", "a", "nuestros", "primos", "los", "fines", "de", "semana."], distractors: ["visito", "nuestras", "prima", "mes"], hint: "Personal a before people.", topic: "Family", cefrLevel: "A2", language: "es" },
  { english: "Their children play outside.", target: "Sus hijos juegan afuera.", words: ["Sus", "hijos", "juegan", "afuera."], distractors: ["su", "juega", "dentro", "niños"], hint: "jugar → juegan.", topic: "Family", cefrLevel: "A2", language: "es" },
  { english: "I get along well with my uncle.", target: "Me llevo bien con mi tío.", words: ["Me", "llevo", "bien", "con", "mi", "tío."], distractors: ["llevas", "mal", "su", "tía"], hint: "llevarse bien = get along.", topic: "Family", cefrLevel: "A2", language: "es" },
  { english: "Even though we argue, we love each other.", target: "Aunque discutamos, nos queremos.", words: ["Aunque", "discutamos,", "nos", "queremos."], distractors: ["discutimos", "me", "quieren", "pero"], hint: "aunque + subjunctive possible.", topic: "Family", cefrLevel: "B1", language: "es" },
  { english: "My parents want me to study medicine.", target: "Mis padres quieren que estudie medicina.", words: ["Mis", "padres", "quieren", "que", "estudie", "medicina."], distractors: ["quiero", "estudio", "padre", "leyes"], hint: "querer que + subjunctive.", topic: "Family", cefrLevel: "B1", language: "es" },
  { english: "She looks like her aunt.", target: "Ella se parece a su tía.", words: ["Ella", "se", "parece", "a", "su", "tía."], distractors: ["parecen", "el", "tío", "miro"], hint: "parecerse a.", topic: "Family", cefrLevel: "B1", language: "es" },
  { english: "We had dinner together last night.", target: "Anoche cenamos juntos.", words: ["Anoche", "cenamos", "juntos."], distractors: ["cenábamos", "junto", "hoy", "comimos"], hint: "Preterite family narrative.", topic: "Family", cefrLevel: "B1", language: "es" },
  { english: "I play soccer.", target: "Juego al fútbol.", words: ["Juego", "al", "fútbol."], distractors: ["juegas", "la", "tenis", "corro"], hint: "jugar → juego; al deporte.", topic: "Sports", cefrLevel: "A1", language: "es" },
  { english: "She runs fast.", target: "Ella corre rápido.", words: ["Ella", "corre", "rápido."], distractors: ["corro", "lento", "ellos", "salta"], hint: "correr regular.", topic: "Sports", cefrLevel: "A1", language: "es" },
  { english: "We swim on Saturdays.", target: "Nadamos los sábados.", words: ["Nadamos", "los", "sábados."], distractors: ["nado", "las", "domingos", "corremos"], hint: "Habitual.", topic: "Sports", cefrLevel: "A1", language: "es" },
  { english: "The team wins.", target: "El equipo gana.", words: ["El", "equipo", "gana."], distractors: ["ganan", "la", "pierde", "juego"], hint: "gana = wins.", topic: "Sports", cefrLevel: "A1", language: "es" },
  { english: "I am training for a race.", target: "Estoy entrenando para una carrera.", words: ["Estoy", "entrenando", "para", "una", "carrera."], distractors: ["soy", "entreno", "un", "partido"], hint: "estar + gerund.", topic: "Sports", cefrLevel: "A2", language: "es" },
  { english: "Do you want to play tennis tomorrow?", target: "¿Quieres jugar al tenis mañana?", words: ["¿Quieres", "jugar", "al", "tenis", "mañana?"], distractors: ["quiero", "juego", "la", "hoy"], hint: "querer + infinitive.", topic: "Sports", cefrLevel: "A2", language: "es" },
  { english: "He scored two goals.", target: "Él marcó dos goles.", words: ["Él", "marcó", "dos", "goles."], distractors: ["marca", "dos", "gol", "anotó"], hint: "Preterite sports.", topic: "Sports", cefrLevel: "A2", language: "es" },
  { english: "Our coach speaks clearly.", target: "Nuestro entrenador habla claro.", words: ["Nuestro", "entrenador", "habla", "claro."], distractors: ["nuestra", "hablan", "entrenadora", "rápido"], hint: "Agreement.", topic: "Sports", cefrLevel: "A2", language: "es" },
  { english: "If we practiced more, we would improve.", target: "Si practicáramos más, mejoraríamos.", words: ["Si", "practicáramos", "más,", "mejoraríamos."], distractors: ["practicamos", "mejoramos", "menos", "mejoraré"], hint: "Imperfect subjunctive + conditional.", topic: "Sports", cefrLevel: "B1", language: "es" },
  { english: "The match was postponed because of rain.", target: "El partido se aplazó por la lluvia.", words: ["El", "partido", "se", "aplazó", "por", "la", "lluvia."], distractors: ["aplaza", "el", "viento", "canceló"], hint: "se + preterite passive sense.", topic: "Sports", cefrLevel: "B1", language: "es" },
  { english: "I suggest that you stretch before running.", target: "Te sugiero que te estires antes de correr.", words: ["Te", "sugiero", "que", "te", "estires", "antes", "de", "correr."], distractors: ["sugiero", "estiras", "después", "caminar"], hint: "sugerir que + subjunctive.", topic: "Sports", cefrLevel: "B1", language: "es" },
  { english: "She has broken the school record.", target: "Ella ha batido el récord de la escuela.", words: ["Ella", "ha", "batido", "el", "récord", "de", "la", "escuela."], distractors: ["has", "batió", "la", "colegio"], hint: "Present perfect.", topic: "Sports", cefrLevel: "B1", language: "es" },
  { english: "The sun is bright.", target: "El sol es brillante.", words: ["El", "sol", "es", "brillante."], distractors: ["está", "la", "luna", "oscuro"], hint: "ser for characteristic.", topic: "Nature", cefrLevel: "A1", language: "es" },
  { english: "Trees have green leaves.", target: "Los árboles tienen hojas verdes.", words: ["Los", "árboles", "tienen", "hojas", "verdes."], distractors: ["tiene", "las", "rojo", "flores"], hint: "tener → tienen.", topic: "Nature", cefrLevel: "A1", language: "es" },
  { english: "I hear the river.", target: "Oigo el río.", words: ["Oigo", "el", "río."], distractors: ["oyes", "la", "mar", "veo"], hint: "oír → oigo.", topic: "Nature", cefrLevel: "A1", language: "es" },
  { english: "It is cold today.", target: "Hoy hace frío.", words: ["Hoy", "hace", "frío."], distractors: ["está", "calor", "ayer", "hay"], hint: "hacer for weather.", topic: "Nature", cefrLevel: "A1", language: "es" },
  { english: "We hike in the mountains.", target: "Caminamos por las montañas.", words: ["Caminamos", "por", "las", "montañas."], distractors: ["camino", "la", "playa", "corremos"], hint: "por for through.", topic: "Nature", cefrLevel: "A2", language: "es" },
  { english: "The flowers smell good in spring.", target: "Las flores huelen bien en primavera.", words: ["Las", "flores", "huelen", "bien", "en", "primavera."], distractors: ["huele", "los", "mal", "verano"], hint: "oler → huelen.", topic: "Nature", cefrLevel: "A2", language: "es" },
  { english: "Don't pick the plants.", target: "No arranques las plantas.", words: ["No", "arranques", "las", "plantas."], distractors: ["arranca", "el", "flores", "cortes"], hint: "Negative command.", topic: "Nature", cefrLevel: "A2", language: "es" },
  { english: "A strong wind closed the park.", target: "Un viento fuerte cerró el parque.", words: ["Un", "viento", "fuerte", "cerró", "el", "parque."], distractors: ["cerró", "una", "abre", "jardín"], hint: "Preterite weather event.", topic: "Nature", cefrLevel: "A2", language: "es" },
  { english: "Unless it snows, we will camp outside.", target: "A menos que nieve, acamparemos afuera.", words: ["A", "menos", "que", "nieve,", "acamparemos", "afuera."], distractors: ["nieva", "acampamos", "dentro", "llover"], hint: "a menos que + subjunctive.", topic: "Nature", cefrLevel: "B1", language: "es" },
  { english: "The lake where we swam is very clean.", target: "El lago donde nadamos está muy limpio.", words: ["El", "lago", "donde", "nadamos", "está", "muy", "limpio."], distractors: ["nadábamos", "es", "la", "sucio"], hint: "donde relative.", topic: "Nature", cefrLevel: "B1", language: "es" },
  { english: "Climate change affects many forests.", target: "El cambio climático afecta a muchos bosques.", words: ["El", "cambio", "climático", "afecta", "a", "muchos", "bosques."], distractors: ["afectan", "muchas", "selva", "cambia"], hint: "afectar a.", topic: "Nature", cefrLevel: "B1", language: "es" },
  { english: "I wish people protected the ocean more.", target: "Ojalá la gente protegiera más el océano.", words: ["Ojalá", "la", "gente", "protegiera", "más", "el", "océano."], distractors: ["protege", "protegemos", "la", "mar"], hint: "ojalá + imperfect subjunctive.", topic: "Nature", cefrLevel: "B1", language: "es" },
  { english: "I drink water every day.", target: "Je bois de l'eau tous les jours.", words: ["Je", "bois", "de", "l'eau", "tous", "les", "jours."], distractors: ["boit", "du", "manger", "toujours"], hint: "boire → bois.", topic: "Daily Life", cefrLevel: "A1", language: "fr" },
  { english: "She opens the window.", target: "Elle ouvre la fenêtre.", words: ["Elle", "ouvre", "la", "fenêtre."], distractors: ["ouvres", "le", "porte", "ferme"], hint: "ouvrir → ouvre.", topic: "Daily Life", cefrLevel: "A1", language: "fr" },
  { english: "We live in a small house.", target: "Nous habitons dans une petite maison.", words: ["Nous", "habitons", "dans", "une", "petite", "maison."], distractors: ["habite", "un", "grande", "appartement"], hint: "habiter regular.", topic: "Daily Life", cefrLevel: "A1", language: "fr" },
  { english: "They wash the dishes.", target: "Ils lavent la vaisselle.", words: ["Ils", "lavent", "la", "vaisselle."], distractors: ["lave", "le", "assiettes", "mangent"], hint: "ils form -ent silent.", topic: "Daily Life", cefrLevel: "A1", language: "fr" },
  { english: "I usually wake up at seven.", target: "D'habitude je me lève à sept heures.", words: ["D'habitude", "je", "me", "lève", "à", "sept", "heures."], distractors: ["lèves", "le", "huit", "réveille"], hint: "Reflexive se lever.", topic: "Daily Life", cefrLevel: "A2", language: "fr" },
  { english: "Can you help me today?", target: "Tu peux m'aider aujourd'hui ?", words: ["Tu", "peux", "m'aider", "aujourd'hui?"], distractors: ["peut", "aider", "demain", "pouvez"], hint: "pouvoir + infinitive.", topic: "Daily Life", cefrLevel: "A2", language: "fr" },
  { english: "We need to buy bread.", target: "Nous devons acheter du pain.", words: ["Nous", "devons", "acheter", "du", "pain."], distractors: ["dois", "achetons", "de", "lait"], hint: "devoir + infinitive.", topic: "Daily Life", cefrLevel: "A2", language: "fr" },
  { english: "The store closes at nine.", target: "Le magasin ferme à neuf heures.", words: ["Le", "magasin", "ferme", "à", "neuf", "heures."], distractors: ["ferment", "la", "huit", "ouvre"], hint: "fermer regular.", topic: "Daily Life", cefrLevel: "A2", language: "fr" },
  { english: "I have already finished my homework.", target: "J'ai déjà fini mes devoirs.", words: ["J'ai", "déjà", "fini", "mes", "devoirs."], distractors: ["as", "finir", "mon", "travail"], hint: "Passé composé.", topic: "Daily Life", cefrLevel: "B1", language: "fr" },
  { english: "If it rains, I stay home.", target: "S'il pleut, je reste à la maison.", words: ["S'il", "pleut,", "je", "reste", "à", "la", "maison."], distractors: ["pleuvoir", "restes", "le", "pleuvait"], hint: "si + present.", topic: "Daily Life", cefrLevel: "B1", language: "fr" },
  { english: "She asked me to wait a moment.", target: "Elle m'a demandé d'attendre un moment.", words: ["Elle", "m'a", "demandé", "d'attendre", "un", "moment."], distractors: ["demande", "attendre", "une", "dire"], hint: "demander de + infinitive.", topic: "Daily Life", cefrLevel: "B1", language: "fr" },
  { english: "We used to walk after dinner.", target: "Nous avions l'habitude de marcher après le dîner.", words: ["Nous", "avions", "l'habitude", "de", "marcher", "après", "le", "dîner."], distractors: ["avons", "marchons", "avant", "la"], hint: "habitude de + infinitive.", topic: "Daily Life", cefrLevel: "B1", language: "fr" },
  { english: "Where is the hotel?", target: "Où est l'hôtel ?", words: ["Où", "est", "l'hôtel?"], distractors: ["suis", "la", "gare", "sont"], hint: "être for location.", topic: "Travel", cefrLevel: "A1", language: "fr" },
  { english: "I need a ticket.", target: "J'ai besoin d'un billet.", words: ["J'ai", "besoin", "d'un", "billet."], distractors: ["as", "une", "ticket", "veux"], hint: "avoir besoin de.", topic: "Travel", cefrLevel: "A1", language: "fr" },
  { english: "The train is late.", target: "Le train est en retard.", words: ["Le", "train", "est", "en", "retard."], distractors: ["sont", "la", "avion", "tôt"], hint: "en retard = late.", topic: "Travel", cefrLevel: "A1", language: "fr" },
  { english: "We go to the airport.", target: "Nous allons à l'aéroport.", words: ["Nous", "allons", "à", "l'aéroport."], distractors: ["vais", "au", "gare", "allez"], hint: "aller → allons.", topic: "Travel", cefrLevel: "A1", language: "fr" },
  { english: "How do I get to the museum?", target: "Comment aller au musée ?", words: ["Comment", "aller", "au", "musée?"], distractors: ["vais", "à", "la", "théâtre"], hint: "au = à + le.", topic: "Travel", cefrLevel: "A2", language: "fr" },
  { english: "Please show me the map.", target: "Montre-moi le plan, s'il te plaît.", words: ["Montre-moi", "le", "plan,", "s'il", "te", "plaît."], distractors: ["montre", "la", "carte", "nous"], hint: "Imperative + pronoun.", topic: "Travel", cefrLevel: "A2", language: "fr" },
  { english: "Our flight leaves at noon.", target: "Notre vol part à midi.", words: ["Notre", "vol", "part", "à", "midi."], distractors: ["notre", "partent", "la", "nuit"], hint: "partir → part.", topic: "Travel", cefrLevel: "A2", language: "fr" },
  { english: "I lost my suitcase yesterday.", target: "J'ai perdu ma valise hier.", words: ["J'ai", "perdu", "ma", "valise", "hier."], distractors: ["as", "perdu", "mon", "aujourd'hui"], hint: "Passé composé.", topic: "Travel", cefrLevel: "A2", language: "fr" },
  { english: "I wish the bus would come soon.", target: "J'aimerais que le bus vienne bientôt.", words: ["J'aimerais", "que", "le", "bus", "vienne", "bientôt."], distractors: ["viens", "vient", "la", "train"], hint: "Subjunctive after aimerais que.", topic: "Travel", cefrLevel: "B1", language: "fr" },
  { english: "By the time we arrived, the gate had closed.", target: "Quand nous sommes arrivés, la porte était déjà fermée.", words: ["Quand", "nous", "sommes", "arrivés,", "la", "porte", "était", "déjà", "fermée."], distractors: ["arrivons", "était", "le", "ouverte"], hint: "Imparfait background.", topic: "Travel", cefrLevel: "B1", language: "fr" },
  { english: "Could you tell me which platform it is?", target: "Pourriez-vous me dire quel quai c'est ?", words: ["Pourriez-vous", "me", "dire", "quel", "quai", "c'est?"], distractors: ["peux", "dites", "quelle", "gare"], hint: "Conditional politeness.", topic: "Travel", cefrLevel: "B1", language: "fr" },
  { english: "We should reserve seats in advance.", target: "Nous devrions réserver des places à l'avance.", words: ["Nous", "devrions", "réserver", "des", "places", "à", "l'avance."], distractors: ["devons", "réserve", "la", "avant"], hint: "Conditional of devoir.", topic: "Travel", cefrLevel: "B1", language: "fr" },
  { english: "I like rice.", target: "J'aime le riz.", words: ["J'aime", "le", "riz."], distractors: ["aimes", "la", "pain", "veux"], hint: "aimer + definite article.", topic: "Food", cefrLevel: "A1", language: "fr" },
  { english: "She eats fruit.", target: "Elle mange des fruits.", words: ["Elle", "mange", "des", "fruits."], distractors: ["manges", "du", "légume", "boit"], hint: "manger regular.", topic: "Food", cefrLevel: "A1", language: "fr" },
  { english: "The soup is hot.", target: "La soupe est chaude.", words: ["La", "soupe", "est", "chaude."], distractors: ["est", "le", "froide", "sont"], hint: "Agreement chaude.", topic: "Food", cefrLevel: "A1", language: "fr" },
  { english: "We want coffee.", target: "Nous voulons du café.", words: ["Nous", "voulons", "du", "café."], distractors: ["veux", "de", "eau", "voulez"], hint: "vouloir → voulons.", topic: "Food", cefrLevel: "A1", language: "fr" },
  { english: "This restaurant serves spicy food.", target: "Ce restaurant sert des plats épicés.", words: ["Ce", "restaurant", "sert", "des", "plats", "épicés."], distractors: ["sert", "cette", "plat", "doux"], hint: "servir → sert.", topic: "Food", cefrLevel: "A2", language: "fr" },
  { english: "I prefer chicken without salt.", target: "Je préfère le poulet sans sel.", words: ["Je", "préfère", "le", "poulet", "sans", "sel."], distractors: ["préfères", "la", "viande", "avec"], hint: "préférer accent.", topic: "Food", cefrLevel: "A2", language: "fr" },
  { english: "Can we order dessert now?", target: "On peut commander le dessert maintenant ?", words: ["On", "peut", "commander", "le", "dessert", "maintenant?"], distractors: ["peux", "commandons", "la", "plus"], hint: "pouvoir + infinitive.", topic: "Food", cefrLevel: "A2", language: "fr" },
  { english: "The market opens early on Sundays.", target: "Le marché ouvre tôt le dimanche.", words: ["Le", "marché", "ouvre", "tôt", "le", "dimanche."], distractors: ["ouvrent", "la", "tard", "lundi"], hint: "Days use le.", topic: "Food", cefrLevel: "A2", language: "fr" },
  { english: "I would try the dish if it weren't so spicy.", target: "Je goûterais le plat s'il n'était pas si épicé.", words: ["Je", "goûterais", "le", "plat", "s'il", "n'était", "pas", "si", "épicé."], distractors: ["goûte", "était", "la", "salé"], hint: "Conditional + imparfait.", topic: "Food", cefrLevel: "B1", language: "fr" },
  { english: "They say this cheese is made nearby.", target: "On dit que ce fromage est fabriqué près d'ici.", words: ["On", "dit", "que", "ce", "fromage", "est", "fabriqué", "près", "d'ici."], distractors: ["disent", "fabrique", "cette", "loin"], hint: "Passive with être.", topic: "Food", cefrLevel: "B1", language: "fr" },
  { english: "Before cooking, wash the vegetables well.", target: "Avant de cuisiner, lave bien les légumes.", words: ["Avant", "de", "cuisiner,", "lave", "bien", "les", "légumes."], distractors: ["laves", "le", "cuisines", "fruits"], hint: "avant de + infinitive.", topic: "Food", cefrLevel: "B1", language: "fr" },
  { english: "I'm full, but the cake smells amazing.", target: "Je suis plein, mais le gâteau sent trop bon.", words: ["Je", "suis", "plein,", "mais", "le", "gâteau", "sent", "trop", "bon."], distractors: ["es", "pleine", "la", "goûte"], hint: "sentir → sent.", topic: "Food", cefrLevel: "B1", language: "fr" },
  { english: "The dog is big.", target: "Le chien est grand.", words: ["Le", "chien", "est", "grand."], distractors: ["est", "la", "chat", "petit"], hint: "être + adjective.", topic: "Animals", cefrLevel: "A1", language: "fr" },
  { english: "Cats drink milk.", target: "Les chats boivent du lait.", words: ["Les", "chats", "boivent", "du", "lait."], distractors: ["boit", "de", "eau", "mangent"], hint: "boire → boivent.", topic: "Animals", cefrLevel: "A1", language: "fr" },
  { english: "I see a bird.", target: "Je vois un oiseau.", words: ["Je", "vois", "un", "oiseau."], distractors: ["voit", "une", "chien", "regarde"], hint: "voir → vois.", topic: "Animals", cefrLevel: "A1", language: "fr" },
  { english: "The fish swims fast.", target: "Le poisson nage vite.", words: ["Le", "poisson", "nage", "vite."], distractors: ["nagent", "la", "lentement", "court"], hint: "nager regular.", topic: "Animals", cefrLevel: "A1", language: "fr" },
  { english: "My horse runs in the field.", target: "Mon cheval court dans le champ.", words: ["Mon", "cheval", "court", "dans", "le", "champ."], distractors: ["courent", "la", "maison", "chevaux"], hint: "courir → court.", topic: "Animals", cefrLevel: "A2", language: "fr" },
  { english: "There are many sheep here.", target: "Il y a beaucoup de moutons ici.", words: ["Il", "y", "a", "beaucoup", "de", "moutons", "ici."], distractors: ["as", "des", "mouton", "là"], hint: "il y a.", topic: "Animals", cefrLevel: "A2", language: "fr" },
  { english: "The baby elephant is cute.", target: "Le bébé éléphant est adorable.", words: ["Le", "bébé", "éléphant", "est", "adorable."], distractors: ["est", "la", "moche", "éléphants"], hint: "Adjective after noun often.", topic: "Animals", cefrLevel: "A2", language: "fr" },
  { english: "Don't feed the animals.", target: "Ne nourris pas les animaux.", words: ["Ne", "nourris", "pas", "les", "animaux."], distractors: ["nourrit", "le", "donne", "animal"], hint: "Negative imperative.", topic: "Animals", cefrLevel: "A2", language: "fr" },
  { english: "If I had a dog, I would walk it daily.", target: "Si j'avais un chien, je le promènerais tous les jours.", words: ["Si", "j'avais", "un", "chien,", "je", "le", "promènerais", "tous", "les", "jours."], distractors: ["ai", "promène", "une", "toujours"], hint: "si + imparfait + conditional.", topic: "Animals", cefrLevel: "B1", language: "fr" },
  { english: "Birds that migrate travel thousands of kilometers.", target: "Les oiseaux qui migrent parcourent des milliers de kilomètres.", words: ["Les", "oiseaux", "qui", "migrent", "parcourent", "des", "milliers", "de", "kilomètres."], distractors: ["migre", "parcourt", "la", "mètre"], hint: "Relative qui.", topic: "Animals", cefrLevel: "B1", language: "fr" },
  { english: "She is afraid of spiders.", target: "Elle a peur des araignées.", words: ["Elle", "a", "peur", "des", "araignées."], distractors: ["as", "peur", "du", "araignée"], hint: "avoir peur de.", topic: "Animals", cefrLevel: "B1", language: "fr" },
  { english: "The zoo closed because the storm arrived.", target: "Le zoo a fermé parce que la tempête est arrivée.", words: ["Le", "zoo", "a", "fermé", "parce", "que", "la", "tempête", "est", "arrivée."], distractors: ["ferme", "arrivé", "le", "pluie"], hint: "Passé composé agreement.", topic: "Animals", cefrLevel: "B1", language: "fr" },
  { english: "I work in an office.", target: "Je travaille dans un bureau.", words: ["Je", "travaille", "dans", "un", "bureau."], distractors: ["travailles", "une", "école", "travail"], hint: "travailler regular.", topic: "Work", cefrLevel: "A1", language: "fr" },
  { english: "She is a teacher.", target: "Elle est professeure.", words: ["Elle", "est", "professeure."], distractors: ["est", "professeur", "sont", "médecin"], hint: "être + profession.", topic: "Work", cefrLevel: "A1", language: "fr" },
  { english: "We start at nine.", target: "Nous commençons à neuf heures.", words: ["Nous", "commençons", "à", "neuf", "heures."], distractors: ["commence", "huit", "finissons", "le"], hint: "ç before o.", topic: "Work", cefrLevel: "A1", language: "fr" },
  { english: "He writes emails.", target: "Il écrit des e-mails.", words: ["Il", "écrit", "des", "e-mails."], distractors: ["écris", "de", "lettres", "lit"], hint: "écrire → écrit.", topic: "Work", cefrLevel: "A1", language: "fr" },
  { english: "I have a meeting this afternoon.", target: "J'ai une réunion cet après-midi.", words: ["J'ai", "une", "réunion", "cet", "après-midi."], distractors: ["as", "un", "matin", "avons"], hint: "cet before vowel sound.", topic: "Work", cefrLevel: "A2", language: "fr" },
  { english: "Could you send the file?", target: "Tu peux envoyer le fichier ?", words: ["Tu", "peux", "envoyer", "le", "fichier?"], distractors: ["peut", "envoies", "la", "document"], hint: "pouvoir + infinitive.", topic: "Work", cefrLevel: "A2", language: "fr" },
  { english: "My boss calls every Monday.", target: "Mon patron appelle tous les lundis.", words: ["Mon", "patron", "appelle", "tous", "les", "lundis."], distractors: ["appellent", "patronne", "chaque", "mardi"], hint: "appeler double l.", topic: "Work", cefrLevel: "A2", language: "fr" },
  { english: "We finished the project yesterday.", target: "Nous avons fini le projet hier.", words: ["Nous", "avons", "fini", "le", "projet", "hier."], distractors: ["finissons", "la", "aujourd'hui", "ai"], hint: "Passé composé.", topic: "Work", cefrLevel: "A2", language: "fr" },
  { english: "I would accept the job if the salary were better.", target: "J'accepterais le poste si le salaire était meilleur.", words: ["J'accepterais", "le", "poste", "si", "le", "salaire", "était", "meilleur."], distractors: ["accepte", "soit", "la", "pire"], hint: "Conditional + imparfait.", topic: "Work", cefrLevel: "B1", language: "fr" },
  { english: "Please let me know when you arrive.", target: "Préviens-moi quand tu arriveras.", words: ["Préviens-moi", "quand", "tu", "arriveras."], distractors: ["préviens", "arrives", "arriver", "nous"], hint: "Future after quand.", topic: "Work", cefrLevel: "B1", language: "fr" },
  { english: "She has been working here for two years.", target: "Elle travaille ici depuis deux ans.", words: ["Elle", "travaille", "ici", "depuis", "deux", "ans."], distractors: ["a", "travaillé", "trois", "là"], hint: "depuis + present.", topic: "Work", cefrLevel: "B1", language: "fr" },
  { english: "The report must be submitted today.", target: "Le rapport doit être remis aujourd'hui.", words: ["Le", "rapport", "doit", "être", "remis", "aujourd'hui."], distractors: ["doivent", "remettre", "la", "demain"], hint: "devoir + être + participle.", topic: "Work", cefrLevel: "B1", language: "fr" },
  { english: "This is my mother.", target: "Voici ma mère.", words: ["Voici", "ma", "mère."], distractors: ["voilà", "mon", "père", "sa"], hint: "ma + feminine.", topic: "Family", cefrLevel: "A1", language: "fr" },
  { english: "I have two brothers.", target: "J'ai deux frères.", words: ["J'ai", "deux", "frères."], distractors: ["as", "deux", "sœurs", "il"], hint: "frère = brother.", topic: "Family", cefrLevel: "A1", language: "fr" },
  { english: "Our grandmother is kind.", target: "Notre grand-mère est gentille.", words: ["Notre", "grand-mère", "est", "gentille."], distractors: ["nos", "est", "grand-père", "sérieux"], hint: "gentille agreement.", topic: "Family", cefrLevel: "A1", language: "fr" },
  { english: "The baby sleeps now.", target: "Le bébé dort maintenant.", words: ["Le", "bébé", "dort", "maintenant."], distractors: ["dorment", "la", "plus", "mange"], hint: "dormir → dort.", topic: "Family", cefrLevel: "A1", language: "fr" },
  { english: "My sister lives with her husband.", target: "Ma sœur vit avec son mari.", words: ["Ma", "sœur", "vit", "avec", "son", "mari."], distractors: ["vivent", "frère", "ma", "femme"], hint: "vivre → vit.", topic: "Family", cefrLevel: "A2", language: "fr" },
  { english: "We visit our cousins on weekends.", target: "Nous rendons visite à nos cousins le week-end.", words: ["Nous", "rendons", "visite", "à", "nos", "cousins", "le", "week-end."], distractors: ["rends", "nos", "cousine", "mois"], hint: "rendre visite à.", topic: "Family", cefrLevel: "A2", language: "fr" },
  { english: "Their children play outside.", target: "Leurs enfants jouent dehors.", words: ["Leurs", "enfants", "jouent", "dehors."], distractors: ["leur", "joue", "dedans", "fils"], hint: "leurs plural.", topic: "Family", cefrLevel: "A2", language: "fr" },
  { english: "I get along well with my uncle.", target: "Je m'entends bien avec mon oncle.", words: ["Je", "m'entends", "bien", "avec", "mon", "oncle."], distractors: ["entends", "mal", "sa", "tante"], hint: "s'entendre bien.", topic: "Family", cefrLevel: "A2", language: "fr" },
  { english: "Even though we argue, we love each other.", target: "Même si on se dispute, on s'aime.", words: ["Même", "si", "on", "se", "dispute,", "on", "s'aime."], distractors: ["disputons", "me", "aiment", "mais"], hint: "même si + indicative.", topic: "Family", cefrLevel: "B1", language: "fr" },
  { english: "My parents want me to study medicine.", target: "Mes parents veulent que j'étudie la médecine.", words: ["Mes", "parents", "veulent", "que", "j'étudie", "la", "médecine."], distractors: ["veux", "étudie", "père", "droit"], hint: "vouloir que + subjunctive.", topic: "Family", cefrLevel: "B1", language: "fr" },
  { english: "She looks like her aunt.", target: "Elle ressemble à sa tante.", words: ["Elle", "ressemble", "à", "sa", "tante."], distractors: ["ressemblent", "son", "oncle", "voit"], hint: "ressembler à.", topic: "Family", cefrLevel: "B1", language: "fr" },
  { english: "We had dinner together last night.", target: "Nous avons dîné ensemble hier soir.", words: ["Nous", "avons", "dîné", "ensemble", "hier", "soir."], distractors: ["dînons", "ensemble", "matin", "mangé"], hint: "Passé composé.", topic: "Family", cefrLevel: "B1", language: "fr" },
  { english: "I play soccer.", target: "Je joue au football.", words: ["Je", "joue", "au", "football."], distractors: ["joues", "à", "tennis", "cours"], hint: "jouer à + sport.", topic: "Sports", cefrLevel: "A1", language: "fr" },
  { english: "She runs fast.", target: "Elle court vite.", words: ["Elle", "court", "vite."], distractors: ["cours", "lentement", "ils", "saute"], hint: "courir → court.", topic: "Sports", cefrLevel: "A1", language: "fr" },
  { english: "We swim on Saturdays.", target: "Nous nageons le samedi.", words: ["Nous", "nageons", "le", "samedi."], distractors: ["nage", "la", "dimanche", "courons"], hint: "Days with le.", topic: "Sports", cefrLevel: "A1", language: "fr" },
  { english: "The team wins.", target: "L'équipe gagne.", words: ["L'équipe", "gagne."], distractors: ["gagnent", "perd", "match", "joue"], hint: "gagner regular.", topic: "Sports", cefrLevel: "A1", language: "fr" },
  { english: "I am training for a race.", target: "Je m'entraîne pour une course.", words: ["Je", "m'entraîne", "pour", "une", "course."], distractors: ["entraînes", "un", "match", "suis"], hint: "Reflexive s'entraîner.", topic: "Sports", cefrLevel: "A2", language: "fr" },
  { english: "Do you want to play tennis tomorrow?", target: "Tu veux jouer au tennis demain ?", words: ["Tu", "veux", "jouer", "au", "tennis", "demain?"], distractors: ["veut", "joue", "à", "aujourd'hui"], hint: "vouloir + infinitive.", topic: "Sports", cefrLevel: "A2", language: "fr" },
  { english: "He scored two goals.", target: "Il a marqué deux buts.", words: ["Il", "a", "marqué", "deux", "buts."], distractors: ["marque", "deux", "but", "noté"], hint: "Passé composé.", topic: "Sports", cefrLevel: "A2", language: "fr" },
  { english: "Our coach speaks clearly.", target: "Notre entraîneur parle clairement.", words: ["Notre", "entraîneur", "parle", "clairement."], distractors: ["nos", "parlent", "entraîneuse", "vite"], hint: "Adverb clairement.", topic: "Sports", cefrLevel: "A2", language: "fr" },
  { english: "If we practiced more, we would improve.", target: "Si nous nous entraînions plus, nous nous améliorerions.", words: ["Si", "nous", "nous", "entraînions", "plus,", "nous", "nous", "améliorerions."], distractors: ["entraînons", "améliorons", "moins", "améliorerai"], hint: "si + imparfait + conditional.", topic: "Sports", cefrLevel: "B1", language: "fr" },
  { english: "The match was postponed because of rain.", target: "Le match a été reporté à cause de la pluie.", words: ["Le", "match", "a", "été", "reporté", "à", "cause", "de", "la", "pluie."], distractors: ["reporte", "le", "vent", "annulé"], hint: "Passive passé composé.", topic: "Sports", cefrLevel: "B1", language: "fr" },
  { english: "I suggest that you stretch before running.", target: "Je te suggère de t'étirer avant de courir.", words: ["Je", "te", "suggère", "de", "t'étirer", "avant", "de", "courir."], distractors: ["suggère", "étires", "après", "marcher"], hint: "suggérer de + infinitive.", topic: "Sports", cefrLevel: "B1", language: "fr" },
  { english: "She has broken the school record.", target: "Elle a battu le record de l'école.", words: ["Elle", "a", "battu", "le", "record", "de", "l'école."], distractors: ["as", "battu", "la", "collège"], hint: "battre → battu.", topic: "Sports", cefrLevel: "B1", language: "fr" },
  { english: "The sun is bright.", target: "Le soleil est brillant.", words: ["Le", "soleil", "est", "brillant."], distractors: ["est", "la", "lune", "sombre"], hint: "être + adjective.", topic: "Nature", cefrLevel: "A1", language: "fr" },
  { english: "Trees have green leaves.", target: "Les arbres ont des feuilles vertes.", words: ["Les", "arbres", "ont", "des", "feuilles", "vertes."], distractors: ["a", "de", "rouges", "fleurs"], hint: "avoir → ont.", topic: "Nature", cefrLevel: "A1", language: "fr" },
  { english: "I hear the river.", target: "J'entends la rivière.", words: ["J'entends", "la", "rivière."], distractors: ["entend", "le", "mer", "vois"], hint: "entendre.", topic: "Nature", cefrLevel: "A1", language: "fr" },
  { english: "It is cold today.", target: "Il fait froid aujourd'hui.", words: ["Il", "fait", "froid", "aujourd'hui."], distractors: ["est", "chaud", "hier", "y"], hint: "il fait + weather.", topic: "Nature", cefrLevel: "A1", language: "fr" },
  { english: "We hike in the mountains.", target: "Nous marchons dans les montagnes.", words: ["Nous", "marchons", "dans", "les", "montagnes."], distractors: ["marche", "la", "plage", "courons"], hint: "dans for in.", topic: "Nature", cefrLevel: "A2", language: "fr" },
  { english: "The flowers smell good in spring.", target: "Les fleurs sentent bon au printemps.", words: ["Les", "fleurs", "sentent", "bon", "au", "printemps."], distractors: ["sent", "les", "mauvais", "été"], hint: "sentir → sentent.", topic: "Nature", cefrLevel: "A2", language: "fr" },
  { english: "Don't pick the plants.", target: "Ne cueille pas les plantes.", words: ["Ne", "cueille", "pas", "les", "plantes."], distractors: ["cueille", "le", "fleurs", "coupe"], hint: "Negative imperative.", topic: "Nature", cefrLevel: "A2", language: "fr" },
  { english: "A strong wind closed the park.", target: "Un vent fort a fermé le parc.", words: ["Un", "vent", "fort", "a", "fermé", "le", "parc."], distractors: ["fermé", "une", "ouvre", "jardin"], hint: "Passé composé.", topic: "Nature", cefrLevel: "A2", language: "fr" },
  { english: "Unless it snows, we will camp outside.", target: "À moins qu'il ne neige, nous camperons dehors.", words: ["À", "moins", "qu'il", "ne", "neige,", "nous", "camperons", "dehors."], distractors: ["neige", "campons", "dedans", "pleuvoir"], hint: "à moins que + subjunctive.", topic: "Nature", cefrLevel: "B1", language: "fr" },
  { english: "The lake where we swam is very clean.", target: "Le lac où nous avons nagé est très propre.", words: ["Le", "lac", "où", "nous", "avons", "nagé", "est", "très", "propre."], distractors: ["nagions", "est", "la", "sale"], hint: "où relative.", topic: "Nature", cefrLevel: "B1", language: "fr" },
  { english: "Climate change affects many forests.", target: "Le changement climatique touche beaucoup de forêts.", words: ["Le", "changement", "climatique", "touche", "beaucoup", "de", "forêts."], distractors: ["touchent", "des", "jungle", "change"], hint: "toucher = affect.", topic: "Nature", cefrLevel: "B1", language: "fr" },
  { english: "I wish people protected the ocean more.", target: "J'aimerais que les gens protègent davantage l'océan.", words: ["J'aimerais", "que", "les", "gens", "protègent", "davantage", "l'océan."], distractors: ["protègent", "protégeons", "la", "mer"], hint: "Subjunctive after aimerais que.", topic: "Nature", cefrLevel: "B1", language: "fr" },
];

export function pickSentence(
  language: string,
  cefrLevel: string,
  topic?: string,
): PickedSentence {
  const level = levelKey(cefrLevel);
  const lang = language === "fr" ? "fr" : "es";
  let pool = EXERCISES.filter((e) => e.language === lang && e.cefrLevel === level);
  if (topic) {
    const topical = pool.filter((e) => e.topic === topic);
    if (topical.length) pool = topical;
  }
  if (!pool.length) {
    pool = EXERCISES.filter((e) => e.language === lang);
  }
  const exercise = pool[Math.floor(Math.random() * pool.length)]!;
  return {
    ...exercise,
    allWords: fisherYates([...exercise.words, ...exercise.distractors]),
  };
}

export function listSentenceTopics(): string[] {
  return ["Daily Life", "Travel", "Food", "Animals", "Work", "Family", "Sports", "Nature"];
}
