export type { TranslationPair } from "./cannon-words-es";
import type { TranslationPair } from "./cannon-words-es";

export const CANNON_PAIRS_FR: TranslationPair[] = [
  { english: "dog", target: "chien" }, { english: "cat", target: "chat" },
  { english: "horse", target: "cheval" }, { english: "bird", target: "oiseau" },
  { english: "fish", target: "poisson" }, { english: "cow", target: "vache" },
  { english: "lion", target: "lion" }, { english: "bear", target: "ours" },
  { english: "red", target: "rouge" }, { english: "blue", target: "bleu" },
  { english: "green", target: "vert" }, { english: "yellow", target: "jaune" },
  { english: "black", target: "noir" }, { english: "white", target: "blanc" },
  { english: "orange", target: "orange" }, { english: "purple", target: "violet" },
  { english: "one", target: "un" }, { english: "two", target: "deux" },
  { english: "three", target: "trois" }, { english: "four", target: "quatre" },
  { english: "five", target: "cinq" }, { english: "ten", target: "dix" },
  { english: "hand", target: "main" }, { english: "eye", target: "oeil" },
  { english: "head", target: "tête" }, { english: "foot", target: "pied" },
  { english: "heart", target: "coeur" }, { english: "mouth", target: "bouche" },
  { english: "water", target: "eau" }, { english: "bread", target: "pain" },
  { english: "apple", target: "pomme" }, { english: "milk", target: "lait" },
  { english: "egg", target: "oeuf" }, { english: "rice", target: "riz" },
  { english: "chicken", target: "poulet" }, { english: "coffee", target: "café" },
  { english: "house", target: "maison" }, { english: "school", target: "école" },
  { english: "city", target: "ville" }, { english: "beach", target: "plage" },
  { english: "street", target: "rue" }, { english: "park", target: "parc" },
  { english: "big", target: "grand" }, { english: "small", target: "petit" },
  { english: "fast", target: "rapide" }, { english: "slow", target: "lent" },
  { english: "good", target: "bon" }, { english: "bad", target: "mauvais" },
  { english: "hot", target: "chaud" }, { english: "cold", target: "froid" },
  { english: "book", target: "livre" }, { english: "car", target: "voiture" },
  { english: "door", target: "porte" }, { english: "sun", target: "soleil" },
  { english: "moon", target: "lune" }, { english: "sky", target: "ciel" },
  { english: "tree", target: "arbre" }, { english: "flower", target: "fleur" },
  { english: "fire", target: "feu" }, { english: "friend", target: "ami" },
  { english: "love", target: "amour" }, { english: "time", target: "temps" },
  { english: "day", target: "jour" }, { english: "night", target: "nuit" },
  { english: "morning", target: "matin" },
];
