/** Spanish vocabulary words for Hangman. 5–12 letters, no accent marks. */
export const HANGMAN_WORDS_ES = [
  // Animals
  "PERRO", "GATOS", "CABALLO", "ELEFANTE", "MARIPOSA", "TORTUGA", "DELFIN",
  "PINGÜINO", "COCODRILO", "SERPIENTE", "AGUILA", "FLAMENCO", "CAMELLO",
  // Food & drink
  "MANZANA", "PLATANO", "NARANJA", "CHOCOLATE", "HELADO", "TORTILLA",
  "ENCHILADA", "TAMALES", "AGUACATE", "ZANAHORIA", "CEBOLLA", "TOMATE",
  "FRIJOLES", "ENSALADA", "LIMONADA", "MERMELADA", "MANDARINA",
  // Household
  "VENTANA", "PUERTA", "COCINA", "DORMITORIO", "BIBLIOTECA", "ESCALERA",
  "ARMARIO", "ALFOMBRA", "LAMPARA", "ESPEJO", "NEVERA", "LAVADORA",
  // Transport
  "AUTOBUS", "BICICLETA", "HELICOPTERO", "SUBMARINO", "MOTOCICLETA",
  "AMBULANCIA", "CAMIONETA",
  // Nature
  "MONTAÑA", "VOLCAN", "TORNADO", "DESIERTO", "PALMERA", "GIRASOL",
  "MARIPOSA", "TORMENTA", "CASCADA", "ARCOIRIS",
  // People & jobs
  "INGENIERO", "ENFERMERA", "CARPINTERO", "PANADERO", "BOMBERO",
  "ARQUITECTO", "PERIODISTA", "MARINERO", "ASTRONAUTA", "DETECTIVE",
  // Objects
  "PARAGUAS", "TELESCOPIO", "ORDENADOR", "CALCULADORA", "MOCHILA",
  "SOMBRERO", "ZAPATILLA", "GUITARRA", "TROMPETA", "MUÑECA",
  // Places
  "AEROPUERTO", "MERCADO", "CATEDRAL", "ESTADIO", "HOSPITAL",
  "RESTAURANTE", "FARMACIA", "MUSEO",
] as const;

export function getRandomHangmanWordEs(): string {
  return HANGMAN_WORDS_ES[Math.floor(Math.random() * HANGMAN_WORDS_ES.length)]!;
}
