/** French vocabulary words for Hangman. 5–12 letters, no accent marks. */
export const HANGMAN_WORDS_FR = [
  // Animals
  "CHIEN", "CHEVAL", "ELEPHANT", "PAPILLON", "TORTUE", "DAUPHIN",
  "PINGOUIN", "CROCODILE", "SERPENT", "AIGLE", "FLAMANT", "CHAMEAU",
  "GIRAFE", "PERROQUET",
  // Food & drink
  "POMME", "BANANE", "ORANGE", "CHOCOLAT", "GLACE", "BAGUETTE",
  "CROISSANT", "FROMAGE", "YAOURT", "CAROTTE", "OIGNON", "TOMATE",
  "HARICOTS", "SALADE", "LIMONADE", "CONFITURE", "MANDARINE",
  // Household
  "FENETRE", "CUISINE", "CHAMBRE", "BIBLIOTHEQUE", "ESCALIER",
  "ARMOIRE", "TAPIS", "LAMPE", "MIROIR", "REFRIGERATEUR", "MACHINE",
  // Transport
  "AUTOBUS", "BICYCLETTE", "HELICOPTERE", "SUBMARINE", "MOTOCYCLETTE",
  "AMBULANCE", "CAMIONETTE", "TRAMWAY",
  // Nature
  "MONTAGNE", "VOLCAN", "TORNADE", "PALMIER", "TOURNESOL",
  "PAPILLON", "ORAGE", "CASCADE", "ARCENCIEL", "FORET",
  // People & jobs
  "INGENIEUR", "INFIRMIERE", "CHARPENTIER", "BOULANGER", "POMPIER",
  "ARCHITECTE", "JOURNALISTE", "MARIN", "ASTRONAUTE", "DETECTIVE",
  // Objects
  "PARAPLUIE", "TELESCOPE", "ORDINATEUR", "CALCULATRICE", "SACADOS",
  "CHAPEAU", "CHAUSSURE", "GUITARE", "TROMPETTE", "POUPEE",
  // Places
  "AEROPORT", "MARCHE", "CATHEDRALE", "STADE", "HOPITAL",
  "RESTAURANT", "PHARMACIE", "MUSEE", "UNIVERSITE",
] as const;

export function getRandomHangmanWordFr(): string {
  return HANGMAN_WORDS_FR[Math.floor(Math.random() * HANGMAN_WORDS_FR.length)]!;
}
