export type PictionaryWord = { word: string; hint: string; category: string };

export const PICTIONARY_WORDS_ES: PictionaryWord[] = [
  // Animals
  { word: "perro",      hint: "dog",         category: "Animals" },
  { word: "gato",       hint: "cat",         category: "Animals" },
  { word: "caballo",    hint: "horse",       category: "Animals" },
  { word: "vaca",       hint: "cow",         category: "Animals" },
  { word: "elefante",   hint: "elephant",    category: "Animals" },
  { word: "tigre",      hint: "tiger",       category: "Animals" },
  { word: "mono",       hint: "monkey",      category: "Animals" },
  { word: "pajaro",     hint: "bird",        category: "Animals" },
  { word: "pez",        hint: "fish",        category: "Animals" },
  { word: "serpiente",  hint: "snake",       category: "Animals" },
  { word: "conejo",     hint: "rabbit",      category: "Animals" },
  { word: "oso",        hint: "bear",        category: "Animals" },
  { word: "leon",       hint: "lion",        category: "Animals" },
  { word: "pato",       hint: "duck",        category: "Animals" },
  { word: "tortuga",    hint: "turtle",      category: "Animals" },
  // Food
  { word: "manzana",    hint: "apple",       category: "Food" },
  { word: "naranja",    hint: "orange",      category: "Food" },
  { word: "pizza",      hint: "pizza",       category: "Food" },
  { word: "helado",     hint: "ice cream",   category: "Food" },
  { word: "pastel",     hint: "cake",        category: "Food" },
  { word: "zanahoria",  hint: "carrot",      category: "Food" },
  { word: "platano",    hint: "banana",      category: "Food" },
  { word: "hamburguesa",hint: "hamburger",   category: "Food" },
  { word: "pan",        hint: "bread",       category: "Food" },
  { word: "queso",      hint: "cheese",      category: "Food" },
  { word: "uva",        hint: "grape",       category: "Food" },
  { word: "sandia",     hint: "watermelon",  category: "Food" },
  // Transport
  { word: "coche",      hint: "car",         category: "Transport" },
  { word: "tren",       hint: "train",       category: "Transport" },
  { word: "avion",      hint: "plane",       category: "Transport" },
  { word: "bicicleta",  hint: "bicycle",     category: "Transport" },
  { word: "barco",      hint: "boat",        category: "Transport" },
  { word: "moto",       hint: "motorcycle",  category: "Transport" },
  { word: "autobus",    hint: "bus",         category: "Transport" },
  // Nature
  { word: "arbol",      hint: "tree",        category: "Nature" },
  { word: "flor",       hint: "flower",      category: "Nature" },
  { word: "sol",        hint: "sun",         category: "Nature" },
  { word: "luna",       hint: "moon",        category: "Nature" },
  { word: "montana",    hint: "mountain",    category: "Nature" },
  { word: "rio",        hint: "river",       category: "Nature" },
  { word: "mar",        hint: "sea",         category: "Nature" },
  { word: "estrella",   hint: "star",        category: "Nature" },
  { word: "nube",       hint: "cloud",       category: "Nature" },
  { word: "lluvia",     hint: "rain",        category: "Nature" },
  // Objects
  { word: "casa",       hint: "house",       category: "Objects" },
  { word: "libro",      hint: "book",        category: "Objects" },
  { word: "pelota",     hint: "ball",        category: "Objects" },
  { word: "mesa",       hint: "table",       category: "Objects" },
  { word: "silla",      hint: "chair",       category: "Objects" },
  { word: "reloj",      hint: "clock/watch", category: "Objects" },
  { word: "sombrero",   hint: "hat",         category: "Objects" },
  { word: "zapato",     hint: "shoe",        category: "Objects" },
  { word: "llave",      hint: "key",         category: "Objects" },
  { word: "corazon",    hint: "heart",       category: "Objects" },
  { word: "cohete",     hint: "rocket",      category: "Objects" },
  { word: "globo",      hint: "balloon",     category: "Objects" },
  // Body
  { word: "mano",       hint: "hand",        category: "Body" },
  { word: "pie",        hint: "foot",        category: "Body" },
  { word: "cabeza",     hint: "head",        category: "Body" },
  { word: "ojo",        hint: "eye",         category: "Body" },
  { word: "nariz",      hint: "nose",        category: "Body" },
  { word: "boca",       hint: "mouth",       category: "Body" },
  { word: "oreja",      hint: "ear",         category: "Body" },
  // Actions (verbs as gerunds)
  { word: "correr",     hint: "running",     category: "Actions" },
  { word: "saltar",     hint: "jumping",     category: "Actions" },
  { word: "nadar",      hint: "swimming",    category: "Actions" },
  { word: "bailar",     hint: "dancing",     category: "Actions" },
  { word: "dormir",     hint: "sleeping",    category: "Actions" },
  { word: "comer",      hint: "eating",      category: "Actions" },
  { word: "beber",      hint: "drinking",    category: "Actions" },
  { word: "leer",       hint: "reading",     category: "Actions" },
  { word: "escribir",   hint: "writing",     category: "Actions" },
  { word: "cocinar",    hint: "cooking",     category: "Actions" },
];

export function getRandomPictionaryWordEs(): PictionaryWord {
  return PICTIONARY_WORDS_ES[Math.floor(Math.random() * PICTIONARY_WORDS_ES.length)]!;
}
