export type { PictionaryWord } from "./pictionary-words-es";
import type { PictionaryWord } from "./pictionary-words-es";

export const PICTIONARY_WORDS_FR: PictionaryWord[] = [
  { word: "chien",      hint: "dog",         category: "Animals" },
  { word: "chat",       hint: "cat",         category: "Animals" },
  { word: "cheval",     hint: "horse",       category: "Animals" },
  { word: "vache",      hint: "cow",         category: "Animals" },
  { word: "elephant",   hint: "elephant",    category: "Animals" },
  { word: "tigre",      hint: "tiger",       category: "Animals" },
  { word: "singe",      hint: "monkey",      category: "Animals" },
  { word: "oiseau",     hint: "bird",        category: "Animals" },
  { word: "poisson",    hint: "fish",        category: "Animals" },
  { word: "serpent",    hint: "snake",       category: "Animals" },
  { word: "lapin",      hint: "rabbit",      category: "Animals" },
  { word: "ours",       hint: "bear",        category: "Animals" },
  { word: "lion",       hint: "lion",        category: "Animals" },
  { word: "canard",     hint: "duck",        category: "Animals" },
  { word: "tortue",     hint: "turtle",      category: "Animals" },
  { word: "pomme",      hint: "apple",       category: "Food" },
  { word: "orange",     hint: "orange",      category: "Food" },
  { word: "pizza",      hint: "pizza",       category: "Food" },
  { word: "glace",      hint: "ice cream",   category: "Food" },
  { word: "gateau",     hint: "cake",        category: "Food" },
  { word: "carotte",    hint: "carrot",      category: "Food" },
  { word: "banane",     hint: "banana",      category: "Food" },
  { word: "hamburger",  hint: "hamburger",   category: "Food" },
  { word: "pain",       hint: "bread",       category: "Food" },
  { word: "fromage",    hint: "cheese",      category: "Food" },
  { word: "raisin",     hint: "grape",       category: "Food" },
  { word: "pasteque",   hint: "watermelon",  category: "Food" },
  { word: "voiture",    hint: "car",         category: "Transport" },
  { word: "train",      hint: "train",       category: "Transport" },
  { word: "avion",      hint: "plane",       category: "Transport" },
  { word: "velo",       hint: "bicycle",     category: "Transport" },
  { word: "bateau",     hint: "boat",        category: "Transport" },
  { word: "moto",       hint: "motorcycle",  category: "Transport" },
  { word: "bus",        hint: "bus",         category: "Transport" },
  { word: "arbre",      hint: "tree",        category: "Nature" },
  { word: "fleur",      hint: "flower",      category: "Nature" },
  { word: "soleil",     hint: "sun",         category: "Nature" },
  { word: "lune",       hint: "moon",        category: "Nature" },
  { word: "montagne",   hint: "mountain",    category: "Nature" },
  { word: "riviere",    hint: "river",       category: "Nature" },
  { word: "mer",        hint: "sea",         category: "Nature" },
  { word: "etoile",     hint: "star",        category: "Nature" },
  { word: "nuage",      hint: "cloud",       category: "Nature" },
  { word: "pluie",      hint: "rain",        category: "Nature" },
  { word: "maison",     hint: "house",       category: "Objects" },
  { word: "livre",      hint: "book",        category: "Objects" },
  { word: "ballon",     hint: "ball",        category: "Objects" },
  { word: "table",      hint: "table",       category: "Objects" },
  { word: "chaise",     hint: "chair",       category: "Objects" },
  { word: "montre",     hint: "watch/clock", category: "Objects" },
  { word: "chapeau",    hint: "hat",         category: "Objects" },
  { word: "chaussure",  hint: "shoe",        category: "Objects" },
  { word: "cle",        hint: "key",         category: "Objects" },
  { word: "coeur",      hint: "heart",       category: "Objects" },
  { word: "fusee",      hint: "rocket",      category: "Objects" },
  { word: "ballon",     hint: "balloon",     category: "Objects" },
  { word: "main",       hint: "hand",        category: "Body" },
  { word: "pied",       hint: "foot",        category: "Body" },
  { word: "tete",       hint: "head",        category: "Body" },
  { word: "oeil",       hint: "eye",         category: "Body" },
  { word: "nez",        hint: "nose",        category: "Body" },
  { word: "bouche",     hint: "mouth",       category: "Body" },
  { word: "oreille",    hint: "ear",         category: "Body" },
  { word: "courir",     hint: "running",     category: "Actions" },
  { word: "sauter",     hint: "jumping",     category: "Actions" },
  { word: "nager",      hint: "swimming",    category: "Actions" },
  { word: "danser",     hint: "dancing",     category: "Actions" },
  { word: "dormir",     hint: "sleeping",    category: "Actions" },
  { word: "manger",     hint: "eating",      category: "Actions" },
  { word: "boire",      hint: "drinking",    category: "Actions" },
  { word: "lire",       hint: "reading",     category: "Actions" },
  { word: "ecrire",     hint: "writing",     category: "Actions" },
  { word: "cuisiner",   hint: "cooking",     category: "Actions" },
];

export function getRandomPictionaryWordFr(): PictionaryWord {
  return PICTIONARY_WORDS_FR[Math.floor(Math.random() * PICTIONARY_WORDS_FR.length)]!;
}
