/** Common French words (3-7 letters, lowercase, no accents) for Word Soup validation */
const RAW_FR = [
  // 3-letter
  "eau","feu","air","sol","mer","lac","riz","roi","loi","cou","dos","bec","age",
  "ami","art","bal","bas","bel","bon","cap","cas","cle","col","cou","cri","dix",
  "don","dou","dur","eco","ecu","eli","est","ete","eux","eve","fat","fer","fil",
  "fin","fis","fit","foi","for","gel","gaz","got","gue","ici","ile","ira","jeu",
  "kit","las","lie","loi","lot","lui","lut","luz","mai","mal","met","mis","mot",
  "mou","mur","nas","net","nez","nom","nor","nos","note","nue","nus","oie","ont",
  "ora","ori","ors","oui","par","pis","peu","pic","pie","pin","pli","plu","pur",
  "que","qui","ras","rue","sec","sel","ses","soi","son","sud","sur","sus","tau",
  "tel","tes","toi","ton","tri","truc","tus","uni","use","vie","vin","vis","vit",
  // 4-letter
  "aise","aime","amis","arme","arbre","aume","aveu","bain","beau","bien","bois",
  "bord","bras","bric","cafe","cage","cake","cale","came","cane","case","cave",
  "chic","choc","ciel","cire","clef","code","coer","coin","cola","coma","cone",
  "cour","cube","cure","dame","dare","date","dent","dieu","dire","doux","drap",
  "duel","duos","ecot","eden","edgo","effi","egot","elle","elus","emas","envi",
  "epee","euro","expo","face","fade","fait","fare","fete","fils","fine","fisc",
  "flan","flou","flux","foin","fond","fore","fort","foie","four","gare","gele",
  "gene","gens","gite","gout","gris","gros","haut","hier","huit","idee","jean",
  "joli","joue","jour","juge","lame","lard","lent","lien","lieu","lime","lion",
  "lire","lobe","loge","loue","louf","loup","lourd","lune","luth","luxe","mais",
  "male","mare","meme","menu","mere","mine","mode","mois","mort","moue","mout",
  "mule","murs","naif","nail","nain","name","nard","nerf","neve","news","noce",
  "noix","nome","nord","nota","nous","nude","nuee","oeuf","onde","once","oral",
  "orge","orme","ordi","over","ovin","page","pani","pans","paon","pare","pari",
  "part","pave","pays","peau","pelé","pere","pert","peso","pied","pile","pion",
  "pipe","plan","plat","ploc","plot","pneu","pore","port","pose","post","pour",
  "prés","prix","proé","prune","puis","puma","rame","rang","rape","rare","rase",
  "rate","real","rein","rire","robe","rocs","rode","role","rome","rude","ruse",
  "sage","sale","sali","same","sang","sans","saur","saut","save","seul","sire",
  "site","soin","soir","sole","some","sort","soue","sous","spot","star","stem",
  "stop","sure","tare","taux","taxi","team","tige","toit","tome","tore","tort",
  "tour","tout","trac","trop","true","tube","type","ulme","veau","vend","vent",
  "venu","vers","vide","vies","vile","viol","vive","void","voie","voir","vole",
  "vote","vous","vrai","yeux","zinc","zone",
  // 5-letter
  "aimer","arbre","balle","blanc","boire","boite","brave","cache","calme","carte",
  "chant","chaud","chose","chien","chemin","claire","clore","coeur","coloc","conte",
  "corps","cours","crime","cycle","dance","debut","delta","drame","droit","ecole",
  "ecrire","email","entre","epais","erreur","etage","fable","femme","ferre","fiche",
  "fleur","forme","force","foret","froid","front","fumee","genre","glace","globe",
  "grace","grade","grand","grive","groge","groupe","guide","hotel","heure","homme",
  "image","jaune","jeune","jolie","jouer","juger","lampe","large","laser","lever",
  "light","livre","local","longs","lumiere","luxuriant","maire","maison","monde",
  "monte","moral","morts","mouvement","musee","nager","nappe","noire","nonce",
  "norme","notre","nuits","nuage","oasis","offre","ombre","onde","ordre","paire",
  "panem","panel","papier","parte","parti","passe","paule","peine","penser","perdu",
  "perte","piano","piece","place","plage","plane","plate","point","porte","posé",
  "poule","poulet","prise","prive","prone","prose","provail","queue","quête","quoi",
  "radio","raile","ranch","rater","recit","regle","rejet","repas","rever","sable",
  "saint","salon","santé","selon","serge","signe","siege","sirène","sobre","solde",
  "sport","stade","store","style","suite","sujet","super","table","temps","tenir",
  "terme","tonal","totale","trace","trait","train","trame","travail","trone","truck",
  "tueur","ultra","union","usine","valse","vaste","vegetal","verre","veste","vieil",
  "vieux","vigne","villa","vitre","vivre","voile","voter","vouloir","voyage","vuide",
  // 6-letter
  "amener","amical","appel","argent","beaute","billet","centre","chance","chasse",
  "cheque","cinema","coiffe","combat","compte","creche","damage","danser","depart",
  "dessin","domaine","donner","douceur","dossier","durite","etoile","entier","existe",
  "expert","fermer","fleche","fonder","garcon","gentil","girafe","greffe","grenat",
  "guider","humeur","jardin","langue","lancer","lapin","lecons","maitre","marche",
  "marier","mature","medecin","membre","merci","mesure","metier","modele","monter",
  "mouton","nation","niveau","nombre","offrir","orange","pardon","partir","pastel",
  "pauvre","peuple","phrase","pierre","pisser","plaire","plante","pointe","police",
  "pomme","possible","potion","poulet","pouvoir","priere","propre","projet","ranger",
  "region","relier","rempli","retard","retour","reunir","rompre","ronger","rosace",
  "rouge","rouler","saison","santon","savant","secret","sentir","servir","signal",
  "simple","social","source","souple","subir","taille","talent","terminer","tigre",
  "titre","touche","tresor","tropique","vassal","ventre","verdure","verset","visite",
];

export const WORD_SOUP_FR: Set<string> = new Set(RAW_FR.map((w) => w.toLowerCase()));

/** Weighted French letters for grid generation */
export const FR_LETTER_WEIGHTS: [string, number][] = [
  ["E",17],["A",8],["I",7],["S",7],["N",7],["T",7],
  ["R",6],["L",6],["U",6],["O",5],["D",4],["C",4],
  ["M",3],["P",3],["V",2],["G",2],["H",2],["F",2],
  ["B",1],["J",1],["Q",1],["Z",1],
];
